* src_shell{doom sync -upj 8 | tee -a CHANGELOG.org; alert} :doom:upgrade:log:
** [2022-06-25 Sat 14:04]
+ Compiling your literate config...
  - Could not read `org-id-values' from /Users/nopan/.config/emacs/.local/cache/.org-id-locations, setting it to nil
  - Tangled 108 code blocks from config.org
  Restarting...
  =✓ Finished in 1.32615s=
  -   * [1.326311] GC count: 1 (0.004784s)
+ Synchronizing your config with Doom Emacs...
  + Regenerating envvars file
    =✓ Generated ~/.config/emacs/.local/env=
  + Installing packages...
    - No packages need to be installed
  + (Re)building packages...
    - No packages need rebuilding
  + Updating recipe repos...
  + Updating packages (this may take a while)...
    + In repository "straight.el", remote "origin" has URL
        "https://github.com/raxod502/straight.el"
             but recipe specifies a URL of
                "https://github.com/radian-software/straight.el.git"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

      How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4) 4
      Really delete remote "origin"? (y or n) y
    * =(5/422) straight.el: e2de88e -> 0e204d4 [12 commit(s)]=
        0e204d4 Add image-mode to straight-built-in-pseudo-packages (#962)
        bc8abcc Fix single quote style in docstrings.
        5fb04bc Add NonGNU ELPA support (#960)
        b6dba13 [#955] Fix straight-vc-git--ensure-local
        03dc146 Rephrase readme that native-comp is now in emacs/master
        9430316 -recipes-org-elpa-retrieve: remove stale org-contrib :includes (#954)
        07cedf0 [#922] Fix 'unambiguous name' error
        d2940b8 [#922] Allow more debugging
        a7a9859 straight--add-package-to-info-path: Only add dirs with "dir" file (#951)
        99ba608 Fix linters
        d4cd480 [#946] Migrate straight.el to radian-software org
        4517e11 Add straight--delete-stderr-file (#940)
    * =(10/422) all-the-icons.el: 65c496d -> ca1ef30 [3 commit(s)]=
        5994e6b Adding appropriate icon for svelte mode
        4eb1a7f Adding svelte icon
        1af8e41 Add crystal lang file and major mode icons
    * =(16/422) dtrt-indent: 66fc30a -> 57f4072 [1 commit(s)]=
        57f4072 Add note about when workaround can be removed
    * =(17/422) helpful: 67cdd10 -> 209971b [4 commit(s)]=
        209971b Check for emacs version in helpful--docstring test
        741b864 Fix advised function docstring test
        2f91e79 Roll version
        c2729a2 Add buttons for shortdoc groups when shortdoc.el is available
    * =(19/422) smartparens: 37f77bf -> ec15aaa [3 commit(s)]=
        ec15aaa feat(python): add auto-colon insert on async def and class
        3ee3baf Add more pairs for OCaml (#1118)
        7e5f169 Add basic 'swift-mode' support
    * =(21/422) projectile: f3468e8 -> 4d6da87 [13 commit(s)]=
        4d6da87 Fix several typos and spelling errors
        e60883f Add variable to enable or disable command caching.
        3931492 [Fix #1654] Add changelog entry for command dedupe fix
        9de18b7 Don't add duplicate commands to command history
        b197256 Add Emacs 28.1 to CI tests
        a4f86f9 Fix byte compile error
        b014d79 Fix version extraction logic
        2807681 Tweak some changelog entries
        e8b0e2c Add a changelog entry
        4fe6b46 Change Grails app project filename to application.yml (#1770)
        405ccc9 Add changelog entry for [#1765] fix
        6b3a73f [Fix #1765] Re-add defaults for src-dir and test-dir
        defce6e Fix support for preset-based installs in CMake projects.
    * =(22/422) project: 4fe1eec -> c52ec93 [6 commit(s)]=
        c52ec93 Update project
        8db769a Update project
        7e6dd97 Update project
        e721db5 Update project
        cad9133 Update project
        81e4dc8 Update project
    * =(24/422) emacs-which-key: 1217db8 -> 1ab1d0c [2 commit(s)]=
        1ab1d0c Add group to minor-mode definition
        1692a1e Add an example to README for keymap binding
    * =(25/422) corfu: bfb0529 -> b825e51 [1 commit(s)]=
        b825e51 Update corfu
    * =(29/422) corfu-doc: 5dd2a29 -> da93136 [1 commit(s)]=
        da93136 Increase the default max width of the doc frame to 80 characters
    * =(32/422) vertico: afd1e1b -> 0bc58ba [3 commit(s)]=
        0bc58ba vertico--history-hash: Improve file name history handling (Fix #242)
        f0347b3 Handle tramp-rfn-eshadow-overlay (Fix #241)
        7ff368e Remove vertico-directory--completing-file-p
    * =(33/422) consult: 4916cda -> 5b7cdb1 [6 commit(s)]=
        5b7cdb1 Fix #599 - Preview was accidentially enabled even for consult-preview-key=nil
        de94f2c consult--temporary-files: Simplify
        cce3e1c Fix consult--temporary-files
        b5af533 Use more verbose symbol
        1ddc88f consult-imenu: Preserve backend faces (Fix #594)
        11384d9 Disable preview for consult-buffer-other-frame (Fix #593)
    * =(43/422) themes: 6aeec22 -> d79a41f [8 commit(s)]=
        d79a41f release: 2.3.0
        026317b docs: correct formatting in project readme
        142554f docs: update theme tables and list
        acddfa1 docs: standardize comment headers
        1793ecc fix(one-light): invisible selection highlights in vertico/selectrum
        0fc2f5d fix(base): make nobreak-space visible again
        0506b1d tweak(manegarm): no fixed-pitch-serif on comments
        fdbcbe1 dev(ci): update and move ci.el
    * =(50/422) doom-modeline: 0986e08 -> 16679e2 [10 commit(s)]=
        16679e2 Bump version to 3.3.2.
        156b024 Fix mouse clicks on mu4e new mail widget
        87d7667 Silence the compiler
        626adbc fix #538: resolve display issue with flycheck-color-mode-line.
        f68fee2 Update FAQ.
        ace3fcb Update README.
        2f2227f Solve the conflicts with solaire faces.
        6d1e8c0 Don't make icons dimmed while unfocusing due to conflicts with solaire.
        550c36f [Compatibility] Support solaire faces.
        b4ba497 [Compatibility] Support flycheck-color-mode-line.
    * =(56/422) treemacs: 0578a1b -> e80c302 [6 commit(s)]=
        e80c302 [Annotations] Fix face annotation invalidation.
        e092411 [Misc] Fix compilation warnings.
        e9f439c [Docs] Add missing faces to readme.
        bb53a69 [Git-Diff] Fix git diffs not showing up at the first start.
        974ff7d [Misc] Add post buffer init hook.
        ac0a514 [Misc] Checkdoc fixes.
    * =(57/422) treemacs-evil was updated indirectly (with treemacs)=
    * =(58/422) treemacs-projectile was updated indirectly (with treemacs)=
    * =(59/422) treemacs-magit was updated indirectly (with treemacs)=
    * =(60/422) treemacs-persp was updated indirectly (with treemacs)=
    * =(69/422) evil: 157af04 -> cc55fa6 [2 commit(s)]=
        cc55fa6 Only look at mark when restoring point in visual state
        7301482 Prompt user to reverse reversed ex range
    * =(97/422) snippets: f74b11b -> 6b2bd5a [3 commit(s)]=
        6b2bd5a fix(org-mode): rm deprecated latex snippet
        919a32f feat(git-commit-mode): add+update git-trailer snippets
        88f6351 dev(ci): pass secrets to workflows (where needed)
    * =(101/422) diff-hl: e84209e -> dabb7be [1 commit(s)]=
        30a54e9 Move misplaced interactive form
    * =(103/422) dirvish: 7294065 -> 867dfc4 [12 commit(s)]=
        867dfc4 fix(subtree): restore subtrees correctly
        e917354 perf: attributes rendering
        c96ab8a perf(menu): avoid unnecessary buffer reverting
        bd3a8ad fix(vc): use "\t" as delimiter in `git-msg` attribute
        437f456 refactor(core): improve the dependencies check at runtime
        90634cd refactor: extract `dirvish-collapse` from `dirvish-extras`
        e1533de perf(subtree): improve efficiency of subtree insertion
        9a31514 refactor: extract out `dirvish-ls` from `dirvish-menu`
        325a165 fix(core): remove killed buffers from `dv-roots`
        e4ab2c7 refactor: move `dirvish-dispatch` to core
        d60380c modify dirvish-cache-dir
        622900d fix(core): get $HOME variable as directory
    * =(110/422) magit: c1fb53d -> bf0ef38 [4 commit(s)]=
        bf0ef382 No longer exit transient while toggling margin or cycling styles
        6a711f1b Make magit-log-merged's number of shown commits configurable
        5e2d1261 magit-dwim-selection: Add forge-edit-topic-draft
        adf5848e Support bookmark-handler-type for Magit bookmarks
    * =(129/422) citeproc-el: ba49516 -> 65e1c52 [8 commit(s)]=
        65e1c52 Correct a docstring typo
        f7bcebf Update testing information in the README
        008710d Don't do CI on Emacs snapshot (for now)
        0e2bef0 Add Emacs 28.1 and update expected fails for CI
        9226eb9 Updated expected fails list
        1af5dc7 Pacify compiler warnings about unescaped single apostrophes
        2462e12 Bump required minimal Emacs version to 26
        fb14b1c Correctly handle missing given names
    * =(150/422) dumb-jump: 1dd5830 -> ba41273 [1 commit(s)]=
        ba41273 Add elisp defmacro rule (#425)
    * =(154/422) lsp-mode: 6b6afc0 -> c8b8cd8 [3 commit(s)]=
        c8b8cd8 `lsp-update-servers` updates all installed servers (#3572)
        aa946a5 fix 80 character width warnings (#3585)
        9957623 Kill LSP buffer local variables during shutdown (#3574)
    * =(158/422) magit was updated indirectly (with magit)=
    * =(159/422) forge: 2cca7c7 -> ed8abda [3 commit(s)]=
        ed8abda Fix table schemata
        3f940aa Fix minimal dependencies
        3b594ab forge-edit-topic-draft: New command
    * =(167/422) pdf-tools: f9ccdf9 -> fe42da6 [3 commit(s)]=
        fe42da6 Minor README change: Remove instruction to install let-alist
        a5b2df9 Remove Emacs 25 from CircleCI test jobs
        d4a333a fix: disable qt-workaround in Emacs 27>=
    * =(174/422) evil-textobj-tree-sitter: fba268b -> f99b7af [1 commit(s)]=
        f99b7af Add fullstop to function docstring
    * =(184/422) cider: b9e1cc2 -> 14246b8 [2 commit(s)]=
        14246b89 Add a changelog entry
        02ac716b Bump cider-nrepl to 0.28.5
    * =(186/422) csv-mode: 53beddc -> e13282b [1 commit(s)]=
        e13282b Update csv-mode
    * =(194/422) emacs-buttercup: ceedad5 -> 42df1fa [1 commit(s)]=
        42df1fa Disable ANSI color sequences in buttercup-reporter-interactive
    * =(212/422) markdown-mode: 1f70977 -> f7cbc96 [2 commit(s)]=
        908717d Fix docstring format issue.
        a597d1c Fix functions with multiple docstrings
    * =(219/422) org: 811deae -> 2b1b428 [14 commit(s)]=
        2b1b42891 org.el (org-read-date): Point to Info documentation
        0dc27a883 oc-basic.el: Stringify year from CSL-JSON date-parts
        7c61a3a80 org-unfontify-region: Handle invisible parts of links
        e7e37c5b2 org-agenda.el: Improve docstrings of agenda date navigation commands
        4a0d951c6 ox-latex tabbing environment support
        f77800c68 org-persist: Avoid overwriting / re-reading unchanged persisted data
        d687aa178 org-persist: Display read errors in echo area
        1c54d75cc org-persist--gc-expired-p: Fix expiry check
        02a22d6fa Backport commit 9a4862a97 from Emacs
        45174d62b Remove XEmacs and ancient Emacs compat code
        9632401dc Auto-Upcase/downcase #+begin/#+end in structure templates
        65e19a081 org-table.el: Fix orgtbl-mode not remapping delete key
        bfd63cc4f org: Improve org-todo handling of negative prefix args
        9fb9a2bdf org.el (org-format-latex-header): Put DEFAULT-PACKAGES before PACKAGES
    * =(238/422) org-re-reveal: 93ba4e9 -> f184e66 [2 commit(s)]=
        f184e66 Version 3.14.1
        94c43ff Encode data-uris without line breaks
    * =(240/422) org-roam: 171a8db -> c386761 [1 commit(s)]=
        c386761 (fix): autoload org-roam-list-files (#2226)
    * =(243/422) ob-restclient.el: 586f1fa -> 3ac834b [1 commit(s)]=
        71fd013 Use `response-body-only` function to hide headers
    * =(253/422) emacs-async: c78bab7 -> 2f57dfa [1 commit(s)]=
        2f57dfa Fix bug-reference-bug-regexp
    * =(266/422) rustic: 35e5352 -> 060149c [3 commit(s)]=
        8b8c6c3 Minor cleanup and doc fixup on cargo install
        90cd031 Implement cargo install
        0bd7932 bump version to 3.2
    * =(288/422) org-jira: c0c0086 -> 44fe1d9 [1 commit(s)]=
        e1cc6bc add user keyword to auth-source-search
    * =(297/422) link-hint.el: a24546e -> 5461229 [3 commit(s)]=
        5461229 Reformat link-hint.el and fix a typo
        f319cea Add link-hint-action-fallback-commands
        dfed198 Add support for epa-key-list-mode
    * =(315/422) org-modern: d0f13dc -> 4131dd8 [6 commit(s)]=
        4131dd8 Minor cleanup
        51ce1fb Cache propertized stars
        a5616ce Rename variable
        7ff8935 Line breaks
        5de3da1 Version 0.4
        ae8797c Restrict org link target regexps (Fix #68)
    * =(326/422) xref: 2ca3069 -> cc312ec [1 commit(s)]=
        cc312ec Update xref
    * =(330/422) compat: 89aa115 -> e1a22bf [2 commit(s)]=
        e1a22bf Update compat
        24bdfa4 Update compat
    * =(350/422) magit-section was updated indirectly (with magit)=
    * =(365/422) parsebib: 83a77ea -> 35e9ced [9 commit(s)]=
        35e9ced Update copyright statement in the README.
        1852390 Update version number to 4.1
        0f13ee3 Add test `parsebib-clean-TeX-markup-nested-macros`.
        249ce8d parsebib-clean-TeX-markup: allow commands in arguments of formatting commands.
        290eeb3 Revert "Move formatting commands to the end of `parsebib-TeX-markup-replacement-alist`."
        363df0b Move formatting commands to the end of `parsebib-TeX-markup-replacement-alist`.
        cc58ef7 Remove test code.
        1cd8cb1 Correctly match `\\$` in parsebib-clean-TeX-markup.
        0c6a724 Untabify parsebib.el
    * =(380/422) ghub: 7beed8c -> 94f5aa2 [7 commit(s)]=
        94f5aa2 ghub-fetch-repository: Fix recent regression
        0e61c0b Support Gitlab GraphQL API
        e6aec51 Cosmetics
        65699aa Put all variables on one line by default
        2c5ba23 Support naming queries
        fb9d33b ghub-fetch-repository: Fetch id on PullRequest and Issue
        2c6671e ghub-fetch-repository: Fetch isDraft on PullRequest
    * =(382/422) yaml.el: c07cc6d -> cb1cc42 [3 commit(s)]=
        e32ef2f add note to yaml-parse-string-with-pos function
        c56d472 add unit test
        69654c2 Fix string values state bug
    * =(402/422) rust-mode: 5f654a5 -> 56e5c3a [3 commit(s)]=
        3e73d67 use rust-buffer-crate to get remote crate path
        332a232 Add some comments documenting the change
        1d4b327 Pass process-environment and exec-path through with-temp-buffer
    * =(405/422) persist: b45d533 -> 78c8d8f [1 commit(s)]=
        78c8d8f Update persist
    =✓ Updated 52 package(s)=
    + (Re)building packages...
      > Building straight...
      > Building all-the-icons...
      > Building dtrt-indent...
      > Building helpful...
      > Building smartparens...
      > Building projectile...
      > Building project...
      > Building project > Building xref...
      > Building project...
      > Building which-key...
      > Building corfu...
      > Building corfu-doc...
      > Building vertico...
      > Building consult...
      > Building consult > Building compat...
      > Building consult...
      > Building doom-themes...
      > Building doom-modeline...
      > Building evil...
      > Building treemacs...
      > Building treemacs-evil...
      > Building treemacs-projectile...
      > Building treemacs-magit...
      > Building treemacs-magit > Building magit...
      > Building treemacs-magit > Building magit > Building git-commit...
      > Building treemacs-magit > Building magit > Building magit-section...
      > Building treemacs-magit > Building magit...
      > Building treemacs-magit...
      > Building treemacs-persp...
      > Building lsp-mode...
      > Building lsp-mode > Building markdown-mode...
      > Building lsp-mode...
      > Building doom-snippets...
      > Building diff-hl...
      > Building dirvish...
      > Building parsebib...
      > Building org...
      > Building citeproc...
      > Building forge...
      > Building forge > Building ghub...
      > Building forge > Building yaml...
      > Building forge...
      > Building dumb-jump...
      > Building async...
      > Building pdf-tools...
      > Building evil-textobj-tree-sitter...
      > Building cider...
      > Building csv-mode...
      > Building buttercup...
      > Building org-re-reveal...
      > Building org-roam...
      > Building ob-restclient...
      > Building rustic...
      > Building rustic > Building rust-mode...
      > Building rustic...
      > Building persist...
      > Building org-jira...
      > Building link-hint...
      > Building org-modern...
      =✓ Rebuilt 52 package(s)=
  + Purging orphaned packages (for the emperor)...
    - No builds to purge
    + Purging ELPA packages...
      * Deleted archives
      * Deleted gpg
    + Purging straight repositories...
      =✓ Purged repos/ace-jump-mode=
    + Regrafting 404 repos...
      =✓ Finished regrafting. Size before: 0.0KB and after: 0.0KB (0.0KB)=
    - No ELN directories to purge
  + (Re)generating autoloads file...
    + Generating autoloads file...
    + Byte-compiling autoloads file...
    =✓ Generated .local/autoloads.28.1.elc=
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
#<process nyan-music>
** <2022-08-09 Tue 20:30>
+ Tangling your literate config...
  Could not read `org-id-values' from /Users/nopan/.config/emacs/.local/cache/.org-id-locations, setting it to nil
  Tangled 113 code blocks from config.org
  * Done tangling 42 file(s)!
+ Synchronizing "default" profile...
  + Regenerating envvars file
    * Generated ~/.config/emacs/.local/env
  + Installing packages...
    + Building citar-embark...
    + Updating recipe repos...
      + Updating recipes for melpa...
      + Updating recipes for gnu-elpa-mirror...
      + Updating recipes for el-get...
      + Updating recipes for emacsmirror-mirror...
    + Cloning minibuffer-header...
    + Building minibuffer-header...
    * Installed 2 packages
  + (Re)building packages...
    - No packages need rebuilding
  + Updating packages (this may take a while)...
    * =(5/428) straight.el: 0e204d4 -> fed2153 [2 commit(s)]=
      fed2153 migrate issue template links to radian software (#979)
      ba36462 Update hook documentation
    * =(6/428) use-package: a7422fb -> 0ad5d9d [1 commit(s)]=
      0ad5d9d Add further notes to the README
    * =(10/428) all-the-icons.el: ca1ef30 -> b18db6b [8 commit(s)]=
      b18db6b config file icons, go config file icons and clean up
      9c90dba support jsonian-mode
      7193403 fix whitespace
      4d7dc19 1. Reverting whitespace 2. Removing default installation subdir.
      d40dfaa Add icons matchers for graphql files & buffers
      8dfe2ff Revert duplicate icon definition
      550d8a3 Add icon for shorthand graphql file extension .gql
      4d6f44c Install to a separate directory.
    * =(16/428) dtrt-indent: 57f4072 -> d4fd1b4 [2 commit(s)]=
      d4fd1b4 Bump version to 1.8
      397ca8e Fix installation instructions (fixes #64)
    * =(17/428) helpful: 209971b -> 94a07d4 [1 commit(s)]=
      94a07d4 Fix advised native-compiled function being treated as primitives
    * =(19/428) smartparens: ec15aaa -> 8b6a3c3 [1 commit(s)]=
      e09ea50 go-mode configs
    * =(21/428) projectile: 4d6da87 -> dc6e7ff [5 commit(s)]=
      dc6e7ff Bump the copyright years
      00fce5a Give the project type "go" higher precedence than universal types (#1785)
      2e4105c Add flag to fd to not print leading "./" (#1784)
      8f2e1ea Switch rails-rspec and rails-test src-dir
      78be771 [Fix #1755] Cache failure to find project root (#1779)
    + =(22/428) Checking out project (2e8da1b)...=
    * =(22/428) project: c52ec93 -> 2e8da1b [1 commit(s)]=
      2e8da1b Update project
    * =(25/428) corfu: b825e51 -> f0d1f1d [8 commit(s)]=
      f0d1f1d Update corfu
      dcdadf0 Update corfu
      b0b9c3f Update corfu
      d79e4e4 Update corfu
      0fa9deb Update corfu
      a24c5ee Update corfu
      c8bd512 Update corfu
      7ea8d26 Update corfu
    * =(28/428) cape: 86a1df6 -> ab2f4ec [15 commit(s)]=
      ab2f4ec cape-file: Fix
      c011123 cape-file: Minor cleanup
      6cfc957 README update
      ad13cc9 README: Generate better info output
      da0bd30 README: Update examples
      be078bf cape-keyword: Update C keywords
      e6903dc README: Fix typos
      b4a6b63 Add cape--wrapped-table to handle table quoting
      c36d740 cape-keyword: Add scheme-mode keywords
      20cdb5b cape-keyword: Formatting
      52b25f5 cape-keyword: Add nim-mode keywords
      6409bb4 README: Prefer cape-file over cape-dabbrev
      7042b04 Version 0.8
      a2b5ed0 Extend README
      9fbce87 Add Capf transformer examples
    * =(30/428) company-mode: d514500 -> f1877a3 [11 commit(s)]=
      3ed6858 company-show-doc-buffer: Add prefix argument toggle-auto-update
      3edab0e Revert "fix company-clang-version function"
      3d97a52 fix company-clang-version function
      95cc174 fix string< test
      73fc888 company-keywords: Add C language keywords
      7b45c29 format it
      4d65fa1 add nim programming language keywords to company-keywords.el
      fa7f55b Update company-keywords.el
      8ae8a2a Update company-keywords.el
      7ef07bd Fix defcustoms syntax
      7bd38c6 CI: Run tests on latest releases
    * =(32/428) vertico: 0bc58ba -> a2e9b1b [21 commit(s)]=
      a2e9b1b vertico-exit: Allow null completion only if explicitly requested
      9c21010 Revert "Remove vertico-directory--completing-file-p" (Fix #260)
      33b178f README: Update comparisons
      e4e0bab README: Update links
      5ec7887 README: Update link
      41f8ed7 README: Update links
      3e04a2a README: Add link to Prot's config
      c1a4f8c README: Add link to Crafted Emacs configuration
      2ad4619 README: Generate better info output
      93f4b55 vertico-directory-enter: Check vertico--base for path completion
      fa97500 README: Link to "Emacs Completion Explained" by Andrew Tropin (@abcdw)
      00b0016 README: Fix typos
      f222187 vertico-repeat-select: Improve completion candidate formatting
      e5af1a3 vertico-repeat: Update commentary
      47ac03f vertico-repeat: Update docstrings
      ab8e871 vertico-repeat: Locally enable recursive minibuffers
      7d52afe vertico-repeat: If called from minibuffer, filter by current command
      2292290 vertico-repeat: Add vertico-repeat-transformers
      29b87fc README update
      7763998 README update
      [...]
    * =(33/428) consult: 5b7cdb1 -> e4546ed [27 commit(s)]=
      e4546ed Use ash instead of lsh (Fix #623)
      39452dd consult-history: Improve display when completing consult-buffer history
      d0e85c5 README: Remove link to superseded icomplete-vertical package
      aaba2b0 Add consult-preview-excluded-files (Fix #621)
      b9c5d9e Remove bookmark preview messages (Fix #414)
      bd6fc14 consult-org-heading: Add tags (Fix #620)
      e0df102 README: Update links to completion systems
      7c5a98a consult-grep: Respect grep-find-ignored-files and grep-find-ignored-directories (Fix #616)
      5d286a6 consult-grep: Minor simplification
      f6e86f3 consult--grep-builder: Use -P and -E which seem more widely supported
      6319aec README: Generate better info output
      054143c consult-history: Report more categories
      1316457 README: Fix typos
      0fa264c consult-async-map: Remap minibuffer-complete-history (Fix #613)
      a7db54e consult--split-setup: Fix
      0195ebf consult--split-setup: Simplify
      2b5f167 consult--split-setup: Fix try completion
      53e78c6 consult-grep/git-grep/ripgrep: Add -F, --fixed-strings support (Fix #608)
      1680f26 consult-xref--preview: Simplify
      634d006 consult-xref: Add preview support for xref-etags-location (Fix #606)
      [...]
    * =(34/428) compat: e1a22bf -> d8967c0 [10 commit(s)]=
      d8967c0 Update compat
      2a9cf8b Update compat
      fe339bd Update compat
      27728fa Update compat
      664be60 Update compat
      cc1924f Update compat
      4680f3c Update compat
      617d6c5 Update compat
      86a63ee Update compat
      f221294 Update compat
    * =(35/428) consult-dir: d397ca6 -> 8abf62d [2 commit(s)]=
      8abf62d Handle "raw" directory strings in recentf-list (fixes #21)
      88f1d7c Remove needless quote and use function-item
    * =(37/428) embark: 63f0d4d -> 5d0459d [4 commit(s)]=
      be28f55 Mark embark-collect-mode as non-interactive
      831f504 Fix embark-recentf-remove (Fix #519)
      70958d0 Remove obsolete consult functions
      9e1d1ef Fix quotation
    * =(38/428) embark-consult was updated indirectly (with embark)=
    * =(39/428) marginalia: 03fa465 -> 69442c2 [6 commit(s)]=
      69442c2 README: Generate better info output
      8a2c5f3 Minor simplification
      ab2ed46 Add "&" as symbol class character for aliases (#144)
      ee2bd92 marginalia-annotate-package: Support longer versions and archive name (nongnu-devel)
      cc2a909 README: Fix typos
      4fe73f5 marginalia--library-doc: Ensure that the fast Bourne shell is used (Fix #143)
    * =(44/428) themes: d79a41f -> aa13e7f [3 commit(s)]=
      aa13e7f dev: add .dir-locals.el
      f943b80 dev: add .doomrc
      5f96ee8 fix(base): solaire-org-hide :foreground bg-alt
    * =(51/428) doom-modeline: 16679e2 -> 1b74638 [40 commit(s)]=
      1b74638 Update comments.
      4c4b451 [Refactor] Improve project-root.
      6438b06 Refactor.
      81666b9 Display misc and time segments in all mode lines.
      ff7af2e [Feature] Make calendar icon optional.
      b818be6 Add 29 into teh issue template.
      b65dd8c Rename face: doom-modeline-date -> doom-modeline-time.
      ab3993c Fix #555: time icon is not shown correctly.
      c536ba3 Update issue template.
      6f30541 Rename segment: date -> time.
      596e524 minor update
      8acbdec add doom modeline support for display-time-mode
      b27d4e3 Fix UT.
      f98f806 Update buffer name while focusing in & out frame.
      61841f9 Update docs for auto style.
      c410a3a Change the auto style.
      7003009 Fix typo.
      700e471 New constant: doom-modeline-ellipsis.
      76df07e Optimize vcs and lsp segments.
      462ff10 Refresh doom-modeline--limited-width-p after reverting the buffer.
      [...]
    * =(55/428) nav-flash: 2e31f32 -> 5d4b485 [1 commit(s)]=
      8b41e13 add Package-Requires field
    * =(57/428) treemacs: e80c302 -> aa3f454 [5 commit(s)]=
      aa3f454 Fix README Typo
      39bc43b [File Management] Change copy/move to optionally include renaming the file.
      1a26094 [Project-Following] Don't follow into $HOME.
      b4701c3 [Project-Following] Make sure to follow only once.
      e266a6a [Project-Following] Fix error when switching caused by annotations.
    * =(58/428) treemacs-evil was updated indirectly (with treemacs)=
    * =(59/428) treemacs-projectile was updated indirectly (with treemacs)=
    * =(60/428) treemacs-magit was updated indirectly (with treemacs)=
    * =(61/428) treemacs-persp was updated indirectly (with treemacs)=
    * =(67/428) writeroom-mode: a736205 -> 1fd5284 [1 commit(s)]=
      1fd5284 Add LICENSE file
    * =(69/428) evil: cc55fa6 -> fdf8a72 [14 commit(s)]=
      fdf8a72 Never kill on visual paste when using evil-paste-before
      48c9286 Save excursion when adding preceeding whitespace to A word
      3045e42 Clear `evil-this-register` when leaving visual state
      5e562ae Add more bindings for evil-window-map
      76b4296 Add more tests for replace-state
      e41151e Revert "Improve on evil-append's determination of eolp"
      477fe8e Add `evil-enter-replace-state` & support replace repetition
      5826a88 Fix daw deleting indentation when deleting the only word in a line
      0e501d1 Remove 24.5 from tests
      f64cdca evil-change only open newline if delete-func deleted line
      a8385a3 Allow setting selected visual area marks
      59158b3 Restore `evil-select-an-object` API
      1c836e4 Restore `evil-select-inner-object` API
      7e67e61 Small fix in 'evil-command-window-ex
    * =(76/428) evil-lion: 4da660e -> a55eb64 [1 commit(s)]=
      94a0087 Update melpa links
    * =(77/428) evil-nerd-commenter: 386cd75 -> b1a9222 [3 commit(s)]=
      b1a9222 fixed byte-compile
      d34ad30 clean code
      ce5ffcc remove elint
    * =(78/428) evil-numbers: 08f0c1e -> 7bd9bb0 [5 commit(s)]=
      7bd9bb0 Cleanup: use pcase-dolist
      bfbe8ea Cleanup: move requirement for ert and evil-numbers into the test
      61dde4e Bump to 0.7
      061f523 Cleanup: quiet un-escaped quote warning
      a6c886d Add Makefile for "make test"
    * =(86/428) evil-collection: ae35410 -> c1ede88 [16 commit(s)]=
      c1ede88 Propertize Misc section correctly
      c08e12c mu4e: update mu4e-main Maildirs section
      c005e07 Revert "mu4e: update mu4e-main Maildirs section"
      b809634 smerge: Add README.org to describe keybindings
      072731a mu4e: update mu4e-main Maildirs section
      8cb3843 unimpaired: repeat-mode integration
      928b107 eldoc: advice-add when Emacs version < 29
      b71d6d6 Corfu: Fix tab declaration
      2fa3609 remove redundant TODO
      926b979 mu4e: replace obsolete functions
      0595cd8 mu4e: delete the redundant keybinding
      7a44d75 mu4e: replace obsolete mu4e-view-save-attachment-multi
      496bbd0 Changed some keys, so user can navigate the cursor during present.
      9cea832 mu4e: Replace obsolete mu4e-headers-search-narrow command
      e1eed25 consult, imenu: Declare some navigation commands to be non-repeatable (#653)
      91e5550 Placate docstring complaint
    * =(90/428) ts-fold: 6cfe36e -> 17d131f [30 commit(s)]=
      17d131f feat(ocaml): Support for ocaml-mode and caml-mode (#24)
      0e83f0e docs(CHANGELOG): update
      5711d9f refactor(parsers): Place it in alphabetic order
      a7c2994 OCaml parser and first functions added (#21)
      0d884a4 refactor(checkdoc): Fix checkdoc warnings (#23)
      401aad7 Readme update (#20)
      54babe5 docs(CHANGELOG): update
      5a94124 fix(indicators): Render indicators once it's mode is enabled (#19)
      ea554f1 Fix a minor typo in ts-fold-parsers.el (#14)
      33e3fb5 docs: changelog
      52d3697 chore(list): sort language alphabetically (#12)
      ae12dd8 Support elixir (#10)
      7f1e24c Add todo note
      4f5ea58 Update copyright year
      2bcb2f3 Fix typo
      551bfeb doc
      e6191cb doc
      d8d6fc0 update
      9a7b17a update
      5be52cd up
      [...]
    * =(91/428) emacs-format-all-the-code: 828280e -> 7e375c0 [10 commit(s)]=
      7e375c0 Simplify error message
      9e61704 Let Prettier infer the parser when it can
      aa22b06 Appease package-lint
      7e047a4 Support `taplo fmt` for TOML
      4101593 Add erb formatter support (#193)
      3227bd4 Sort prettierd language names
      5974bc5 Drop "RJSX" and "Javascript-IDE" from prettierd (#189)
      08d58ca Re-indent prettierd definition
      99fc3f9 Added support for prettierd
      9c8b304 Add alejandra formatter for Nix
    * =(97/428) snippets: 6b2bd5a -> f957f8d [5 commit(s)]=
      f957f8d dev: add .doomrc
      6418bf9 dev: add .dir-locals.el
      8db3a39 snippet(doom-docs-org): add notice-*
      cc9fa46 feat(+php-laravel-mode): add migration snippet
      edd1645 feat(+php-laravel-mode): add __ snippet
    * =(102/428) dired-rsync: b327971 -> 4057a36 [2 commit(s)]=
      4057a36 README.org: document a gotcha with remote-to-remote copy
      7bdc1dd dired-rsync: better file path handling
    * =(103/428) dirvish: 867dfc4 -> 845cd61 [140 commit(s)]=
      845cd61 refactor(vc): improve setter of `dirvish-vc-preview` option
      5f1ab93 refactor(collapse): use `thread-last`
      cfb9d9f fix(core): select prev entry after `dired-up-directory`, closes #120
      8e186f7 fix(collapse): endless while loop
      37c9c3d refactor: improve buffer/window initialization
      b9969e2 feat(core): add `dirvish-hide-cursor` user option, closes #119
      3605ab1 refactor(core): inhibit `moody-redisplay` in dirvish, closes #118
      c2ae189 docs: move FAQ section to CUSTOMIZING.org
      c62f8b8 refactor(core): rename `dirvish-mode/header-line-position`
      8f1b38d refactor(core): make `dirvish--hide-dired-header` a regular function
      b7023b4 refactor(vc): make `vc-annotate` quiet
      95973cf fix(#115): second attempt
      7753e81 refactor(core): improve cursor hiding mechanism
      884abea fix(extras): add offset when aligning text in TTY sessions (#115)
      ceecf18 fix(core): remove `mod` from `dirvish-audio-exts`, closes #114
      db0f289 doc: duplicate keymap in sample config
      030457d feat(extras): add `dirvish-copy-remote-path` command, closes #110
      ba2594f refactor: add `on-winconf-change` slot, closes #112
      ddba662 fix: ensure dedicated dirvish windows
      d87ba9e refactor: improve `dirvish-dispatch`
      [...]
    * =(110/428) magit: bf0ef38 -> 8a0cc83 [15 commit(s)]=
      8a0cc83e magit-push-implicitly--desc: Account for local upstream
      64cca913 magit-push: Fix magit-push-implicitly--desc
      ac7fae6a Set coding system for remaining libraries that need it
      765069ad readme: Use smaller donation images
      24f079e8 readme: Remove spaces between donation images
      b293d305 readme: Update image urls
      0e451f2c Update donation options
      281f0c3c magit-commit-diff-1: Fix recent regression in --all handling
      80cdadb0 magit-section-goto-successor--same: Work around Emacs 26 bug
      acd26dd9 manual: Fix command name for magit-toggle-git-debug entry
      1f7a2937 magit-mode-menu: Fix "Show manual" command
      35da95e9 magit-push-*--desc: Remove newline at end of description
      fd2feb4a magit-push-to-remote: Define using transient-define-suffix
      19461258 magit-push-implicitly: Improve docstring
      12b415e0 magit-push-implicitly--desc: Return desc for push.default=nothing
    + =In repository "git-timemachine", remote "origin" has URL=
      "https://gitlab.com/pidu/git-timemachine.git"
      but recipe specifies a URL of
      "https://codeberg.org/pidu/git-timemachine"

      1) Abort
      2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
      3) Rename remote "origin" manually, re-create it with correct URL, and fetch
      4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
      5) Delete remote "origin", re-create it with manually set URL, and fetch
    * =(122/428) flycheck: c955fd6 -> 8541a61 [4449 commit(s)]=
      ddadb173 Reformat flycheck-test.el so that ‘make check’ succeeds
      199e8059 Fix dependency on bazel.el.
      be3fa604 Fix small issues found by Checkdoc
      541f2085 Stay within line length limit
      29c64a1e Use /usr/bin/python3 since Python 2 is dead
      278905a6 Add missing closing parentheses
      94b46fe7 Add column support to Erlang checkers (#1914)
      afae1391 Adapt the Bazel checkers to changes in bazel-mode.
      301059bb Add rdc=true
      39b35c62 Add -gencode option for cuda-nvcc
      a9714c28 Newer hlint can produce error spans
      59c52375 Update verilator patterns
      71f71df0 Fix a typo in a comment
      31fcad76 Bump version after releasing 32 (closes GH-1754)
      3b5b4248 Release version 32
      3bad72cc Make R linter `lintr` stateless and efficient
      30a65816 Fix Buttercup tests on Emacs 28.
      b3d14923 Update the config file var declarations of pylint and mypy
      041b6341 Add a :working-directory to flake8, pyright, and mypy
      01e01e17 Add a :working-directory property to python-pylint
      [...]
    * =(124/428) flycheck-posframe: 8f60c9b -> 19896b9 [4 commit(s)]=
      110d6eb Fix checkdoc warning surfaced via new github actions check
      cb08f51 Don't test older unsupported emacs versions in github actions
      d9695cf Add github actions workflow
      f46132c Add an option to match the border face to the highest error level.
    * =(125/428) emacs-spell-fu: 1299bfc -> bfd017f [4 commit(s)]=
      bfd017f Cleanup: use `zerop`
      87fd352 Cleanup: sharp-quote function
      dd35cff Cleanup: quiet quote warnings
      4b38ed7 Correct URL
    * =(128/428) citar: b6cd49f -> 146f2cb [33 commit(s)]=
      146f2cb Regeneralize citar-open-entry
      c48f15b Fix README typos
      7e66f53 Make file opening more customizable
      ce0be81 Minor refactor of `citar-add-file-to-library` (#671)
      64c332a Fix: use case-insensitive lookup for bib entry field names.
      bc61a81 Fix autoload issue + multiple selection corner case
      58640a7 Remove citar--clean-string
      8475c1f `citar-open` and `citar-open-notes` now allow creating notes.
      88f7d95 API: resource getter functions now return hash tables.
      c5ed78e Fix bug in citar-capf--candidates
      c05dce0 Allow `citar-select-refs` to be used with `embark-act`.
      96a567d Minor refactoring of `citar--select-resource`
      68f1ef8 Add function to check validity of notes source plists.
      9115f8d Update `citar-open` and related functions to properly handle notes.
      9e0edce Fix undefined variable error for `embark-default-action-overrides`
      3e7d3a4 Include cross-referenced keys when getting note items.
      c02dac7 Fix `citar-file-test--parse-file-field` for new function signature.
      dbc849b Fix indentation and doc string lint warnings.
      1257ebf Remove extra entries argument to API functions
      ba1f700 Add citar-open-notes to embark multitarget-actions
      [...]
    * =(129/428) citar-embark was updated indirectly (with citar)=
    * =(130/428) parsebib: 35e9ced -> 175a1bd [4 commit(s)]=
      175a1bd Update README.md
      ca7f5fc Update version number to 4.2
      994b658 Exclude certain fields when cleaning TeX markup.
      1ec276b Add LICENSE file
    * =(131/428) citeproc-el: 65e1c52 -> 406bd99 [24 commit(s)]=
      f571620 Add acknowledgement section to README
      d2f1845 List new modes in README.md
      42d588e Add tests for the new bib-entry, locator-only and title-only modes
      6f2d024 Add extra citation modes
      7cc0152 Bump copyright year
      73b08e1 Sort only sub-bibs containing repeated items
      eefdcca Add more detailed subbib-filter documentation to README
      b88b2bc Add blt-type field in bib(la)tex->csl conversion tests
      392106d Fix type of the added blt-type entry fields
      6f54885 Add support for csl-type and function based subbib filtering
      b57582f Store the original type during bib(la)tex->conversion
      54843c9 Add name post-processing hook
      aec3657 Add name post-processing hook
      6c928c6 Update expected fails
      4cc0f7f Add name post-processing hook
      e65b44d Add a formatted citation postprocessing hook
      f7bcebf Update testing information in the README
      008710d Don't do CI on Emacs snapshot (for now)
      0e2bef0 Add Emacs 28.1 and update expected fails for CI
      9226eb9 Updated expected fails list
      [...]
    * =(133/428) emacs-howdoyou: a01971a -> f6c659a [2 commit(s)]=
      f6c659a should show howdoyou buffer in new window within current frame
      faf2b8a simplfy how to get window to show buffer
    * =(135/428) realgud: 3c88611 -> 45f7e44 [1 commit(s)]=
      5c596c4 Update README.md by changing a single quantifier
    * =(137/428) dap-mode: 50c2a99 -> e2a37cc [6 commit(s)]=
      e2a37cc Use 'cwd' and 'program' arguments only if they exist (#648)
      31f92f6 Fix typo: brekapoints -> breakpoints (#644)
      157bc48 dap-dlv-go: parse env files on emacs side
      ad0b8f9 Fix dap--select-thread-id after dap--get-path-for-frame change (#641)
      5e449c8 Feature/docker aware dap mode (#559)
      d3c663f dap--select-thread-id: prefer traces w/ valid path (#584)
    * =(140/428) docker.el: 44f0bbe -> 8d0429d [8 commit(s)]=
      8d0429d Disable docstrings warnings for Emacs 28.1
      c74d878 Add missing periods in docstrings
      a14957f Add missing json require
      064bd80 Remove useless vterm requires
      ee3b1c5 Only use json-mode if it's already present
      960193e Test Emacs 28.1
      bc11d5e Version 2.2.0
      9f58cbe Use `json-mode` instead of `js-mode` for `docker-inspect`
    * =(142/428) dockerfile-mode: b63a3d1 -> c7e4e25 [2 commit(s)]=
      c7e4e25 updating build string example
      74ed3df feat(build): add option to specify --progress flag
    * =(146/428) fzf.el: d61cecb -> 21912eb [3 commit(s)]=
      21912eb Add support for custom narrowing (#73)
      7d32bb3 add configurable grep; fzf/grep-dwim (#71)
      978a9d9 stop setting FZF_DEFAULT_COMMAND (#70)
    * =(152/428) dumb-jump: ba41273 -> 0a783d1 [2 commit(s)]=
      0a783d1 remove snapshot
      c560d4e ci: Add Emacs 28.1 (#427)
    * =(155/428) osx-dictionary.el: 1a4479d -> 0715e5a [1 commit(s)]=
      de51869 use current-word to get word to read, avoid only read first syllable
    * =(156/428) lsp-mode: c8b8cd8 -> ece9bcd [43 commit(s)]=
      ece9bcd Don't prompt for an action within `lsp-organize-imports`, even if `lsp-auto-execute-action` is disabled. (#3662)
      d9317f2 Add configuration for excluding declarations from xrefs/references (#3655)
      0f56580 feat(clients): add support for the syntax_tree Ruby gem (#3653)
      b02bde6 bug: fix callback is not when install package from npm (#3656)
      e33fa71 typo/code fix CPP-guide (#3654)
      3fef341 Remove spurious window.showMessage client capability (#3652)
      6d6d997 docs(links): Update install instruction for lsp-grammarly (#3651)
      9ef89a2 docs(links): Update install instructions and links for html/css/json language server (#3649)
      2c6a0e9 Set includeDeclaration to t by default
      4c17f92 Auto-load lsp-racket
      b2dc841 Add Support for Spacemacs (#3620)
      9200482 add `workingDirectory` support to `eslint` client (#3592)
      9a5750b Add client configuration for Marksman (#3632)
      2ca7364 Add option `lsp-purescript-formatter` (#3631)
      4af9907 terraform docs: Fix rendering of lists (#3633)
      6b0c94b terraform: Add documentation related to links (#3630)
      5a62d4a Tweak semantic tokens for terraform (#3626)
      e1d5649 Add `lsp-use-workspace-root-for-server-default-directory' (#3327)
      e4cc46d openscad: better server; support both stdio and tcp connection types (#3514)
      5e511ba fix: clojure-lsp download link using macos arch (#3622)
      [...]
    * =(157/428) lsp-ui: ca195f3 -> 8d4fa5a [7 commit(s)]=
      8d4fa5a Fix typo in `lsp-ui-doc-position` docstring (#725)
      9a8983d bump version to 8.0.1
      a94bcec Fixes for lsp-ui-doc-glance (#711)
      0a6368d Refactor `imenu` option to fix window width, and add note.
      267a2c9 Add an option that will impose `window-size-fixed` on `imenu` buffer.
      11a3a65 More rigorous fix, as per Issue #474.
      84e592e Fix `lsp-ui-imenu' sub-title ordering.
    + =In repository "lsp-bridge", remote "origin" has URL=
      "https://github.com/thaenalpha/lsp-bridge.git"
      but recipe specifies a URL of
      "https://github.com/manateelazycat/lsp-bridge.git"

      1) Abort
      2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
      3) Rename remote "origin" manually, re-create it with correct URL, and fetch
      4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
      5) Delete remote "origin", re-create it with manually set URL, and fetch

       How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4)       Really delete remote "origin"? (y or n)     + Repository "lsp-bridge" has a dirty worktree:
    
       M  README.md
       A  langserver/intelephense.json
       M  lsp-bridge.el

       1) Abort
       2) Stash changes
       3) Discard changes (Choose this if unsure)

       How to proceed? (1, 2, 3; don't know? Pick 3) Optional stash message:     + In repository "lsp-bridge", HEAD on "intelephense" is behind default branch "master"

       1) Abort
       2) Checkout "master"
       3) Magit log "intelephense..master" and open recursive edit

       How to proceed? (1, 2, 3)     * (159/428) lsp-bridge: c0b0bdf -> 0eaa6b3 [230 commit(s)]
       0eaa6b3 Fixed acm telega backends completion not working. (#303)
       91076e1 Refactor code.
       82e0e18 Add telega username completion backend. (#301)
       6e2b467 Update readme.
       12e4c1b Update readme.
       69ec0f9 Add orjson support.
       b464dc3 Refactor with pick_multi_server_names
       d95931f Rename.
       977f565 Refactor: remove duplicate code.
       bc32bba Fix acm-backend-lsp-filepath error.
       18b5ffa Try to fix error: acm-backend-lsp-filepath is void variable
       fe2ff22 Fix issue 299
       6065a0e Ascertain `acm-backend-lsp-filepath` is not void before lsp-bridge-diagnostics-fetch runs (#296) (#297)
       d4adb96 Catch FileNotFoundError when read search files. (#295)
       8934e63 fix: acm-doc-toggle error:frame not exists when acm-enable-doc set to nil (#294)
       9493198 Update readme.
       40b3a05 Update README (#293)
       23e63bb fix: doc preview display (#292)
       062faca feat: add acm elisp symbol type: feature, special form, constant (#291)
       69f390c Add R's languageserver for ess-r-mode (#290)
       [...]
    * =(160/428) magit was updated indirectly (with magit)=
    * =(164/428) code-review: d38fbe5 -> 95b36ec [10 commit(s)]=
      c26a944 fix changelog
      688cc47 remove emacs 25.1 from the list
      3e552d3 fix CI deps
      7010691 fix test suite
      3e54b29 set of fixes
      2a66db3 orient users to enable emojify to see pretty symbols
      eb454fc fix display with long messages. display only first for now
      c267bac Fix suggestion code block
      fa12dc2 doom emacs users
      68f861e remove funding as I've not been active enough here.
    * =(169/428) pdf-tools: fe42da6 -> bb0b71f [8 commit(s)]=
      bb0b71f Change the default value of `pdf-annot-list-highlight-type`
      8e500e5 Fix: Handle nil return value from `image-scroll` functions
      efd4cee pdf-annot: Add function to sort the date field
      0b8d47d Fix: Dockerfile for ubuntu-18/20 needs fix-missing
      4d53fd2 Disable pixel-scroll-precision-mode locally if enabled
      a72fc93 Fix `revert-buffer` for PDF files opened via Tramp
      24e7095 Test and Documentation changes: dockerfiles and readme
      386dca5 Make sure autoconf is install on macOS so autoreconf may run
    * =(173/428) kurecolor: d17a77d -> 2016973 [7 commit(s)]=
      2016973 1.3.2 bump
      c1601a5 Fix error with adjustment functions
      8fa0b29 Bump to 1.3.1
      1bec9d3 Fix error with region functions
      db71be8 Update README (fix some conversion issues)
      b06039b Several new features see below.
      7fcb147 Add clamp & hex set h, s or b from another color + tests.
    * =(176/428) evil-textobj-tree-sitter: f99b7af -> 7ec5835 [3 commit(s)]=
      7ec5835 Update tree-sitter queries to latest
      9dce8da Update tree-sitter queries to latest
      d6dae90 Update tree-sitter queries to latest
    + =In repository "evil-terminal-cursor-changer", remote "origin" has URL=
      "https://github.com/kisaragi-hiu/evil-terminal-cursor-changer.git"
      but recipe specifies a URL of
      "https://github.com/7696122/evil-terminal-cursor-changer.git"

      1) Abort
      2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
      3) Rename remote "origin" manually, re-create it with correct URL, and fetch
      4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
      5) Delete remote "origin", re-create it with manually set URL, and fetch

       How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4)       Really delete remote "origin"? (y or n)     + In repository "evil-terminal-cursor-changer", HEAD on default branch "master" has diverged from "origin/master"

       1) Abort
       2) Merge "origin/master" into "master"
       3) Rebase "master" onto "origin/master"
       4) Reset "master" to "origin/master"
       5) Magit log "master...origin/master" and open recursive edit

       How to proceed? (1, 2, 3, 4, 5)     * (180/428) evil-terminal-cursor-changer: 24755a1 -> 12ea9c0 [70 commit(s)]
       12ea9c0 fix: on tmux
       66403b9 Update evil-terminal-cursor-changer.el
       81ede5c Remove dependency of evil
       582b1ce fix
       c78c506 Add customizable terminal type override, resolves #24
       1cf452c Do nothing when noninteractive is non-nil
       17386ec fix for emacsclient
       46b71ea Make sure a valid escape sequence is always returned
       b16f0da make showing cursor shape reliably
       c2eaa55 double check (display-graphic-p) in etcc--evil-set-cursor
       ca3577d Check for tmux in xterm and wrap seq if true
       918a741 Update README.md
       12d6a33 Make on/off function
       af31670 Add hook for change buffer
       655d028 Modify comment for cursor setting
       2735a11 remove dependency to hexrgb.
       98b50b0 Fix konsole.
       c6d9270 extract cursor shape symbol from cursor type
       ae7c270 update cask file
       1db58dc broken on transparent iterm2 #7
       [...]
    * =(181/428) paredit: 8330a41 -> d0b1a2f [7 commit(s)]=
      d0b1a2f Bump copyright year.
      4a1450b Respect fill-paragraph-function.  Fall back to lisp-fill-paragraph.
      568d4d4 More slurpage edge cases.
      2ecb5f0 Test some backward-slurp screw cases.
      86f1f5f Stop each test on first failure or unexpected success.
      84e8ccd Add some examples of slurping edge cases that we should handle.
      c6300b9 Batch up test failures and implement expected-failure.
    * =(184/428) clojure-mode: b6f41d7 -> ad322e9 [9 commit(s)]=
      ad322e9 v5.15.1
      f38ca72 Use constant values instead of variables in clojure-match-next-def tests (#627)
      cb0f9a9 [Fix #625] Fix imenu displaying metadata instead of var name  (#626)
      bb327cb Tweak a couple of changelog entries
      93bb1c5 v5.15.0
      6952067 Satisfy docstring linter
      54a62cc Fix infinite loop when reverse searching for next definition (#624)
      fee38d7 Add missing clojure.core macros to clojure-mode font-lock declaration: (#623)
      d82417c Remove needless quote of choice values
    * =(185/428) clj-refactor.el: f368c56 -> 1bd7b09 [12 commit(s)]=
      1bd7b09 Use refactor-nrepl 3.5.4
      8f511ea Update circle-ci environment to include value for TERM
      35cca56 Fix regex for removing prefix from ns alias
      7011b06 Remove prefixes including digits and various orderings
      10633c1 Change `cljr-ns-alias-at-point` to detect symbols at point before /
      ead4813 Extract cljr--alias-here helper and add pending test cases with issue
      61249b2 tests for ns-alias-at-point, unresolved-alias-ref, insert-require-libspec
      7398af1 Decomplect finding valid aliases from candidate namespace generation
      9f7ce86 Extract cljr--ns-alias-at-point helper from cljr--magic-requires-lookup-alias
      d061175 Extract cljr--insert-require-libspec helper from cljr-slash
      7bf500c Upgrade refactor-nrepl
      c3b69b3 Upgrade `cider`, `parseedn` and `inflections` dependencies
    * =(186/428) cider: 14246b8 -> 9577dbb [11 commit(s)]=
      9577dbbd [Fix #3235] Fix TRAMP file handling (#3237)
      21ccc40d Use `clojure-mode` 5.15.1 (#3230)
      fe397a56 Fix shell quoting in Gradle tests (#3229)
      486a924e Update cider-tests to reference cider-nrepl 0.28.5
      3377d9d0 Document Gradle usage
      773cc972 Support injecting dependencies into Gradle
      c2744a85 For Gradle jack-in use wrapper by default
      c1bd60e3 Don't disable Gradle daemon by default
      f422665f Populate completions with metadata (#3226)
      b47fe53b `cider-clojure-cli-aliases` should be a string value that need to be explicitly stated (#3224)
      186b4976 [Fix #3200] Improve browse-ns interface with filters and groupings (#3217)
    * =(192/428) elisp-def: dfca043 -> 1d2e88a [2 commit(s)]=
      223a962 Push current position to mark ring
      7e9c950 Silence Emacs deprecation warning
    * =(193/428) elisp-demos: 01c301b -> 4b51dff [1 commit(s)]=
      4b51dff * elisp-demos.org: Update for Emacs 28.2 (Mostly finished).
    * =(196/428) emacs-buttercup: 42df1fa -> 62176a3 [1 commit(s)]=
      62176a3 Improve buttercup--run-suite docstring
    * =(197/428) graphql-mode: 9740e40 -> 92136cf [4 commit(s)]=
      5975f0d Use graphql-beginning of query for indentation
      809464a Don't use loop to navigate code
      4d075a9 Basic support for better indenting in polymode
      0fb22dd Fix syntax table for triple quotes
    * =(200/428) typescript.el: f2de3f4 -> d1123e0 [11 commit(s)]=
      b650e42 fix(fontlock): only re-fontify method calls with reserved words
      9bd226b fix(fontlock): do not fontify builtins in object/interface key context
      84bab53 test(fontlock): update tests related to arglist fontification
      d21c983 feat(fontlock): fontify arrow fn arguments
      ba04745 fix(fontlock): fontify return type in a function type definition
      367cfb7 fix(fontlock): do not fontify function calls as keywords
      93e1040 feat(tests): use font-lock-ensure instead of font-lock-fontify-buffer
      83bf47e Update README.md
      218a546 fix(fontlock): fontify parameters in multiline arglist
      333a7c5 feat(fontlock): fontify the variable and type in typeguard
      d223ae4 style: fix whitespace
    * =(209/428) tide: 96bfc5d -> 4cf6a0d [1 commit(s)]=
      7996277 Describe the behaviors of tide-documentation-at-point and tide-error-at-point better.
    * =(213/428) lua-mode: 5a9bee8 -> d17a00c [1 commit(s)]=
      7442552 Upgrade license to GPLv3
    * =(214/428) markdown-mode: f7cbc96 -> 0b8dc23 [3 commit(s)]=
      fe52190 Don't override link/reference brackets/parentheses faces
      c4f0889 Don't override table faces by link faces
      4b84ecf Improve docstrings
    * =(219/428) nix-mode: 8fe2ccf -> b3f71c7 [436 commit(s)]=
      8bd12b1 fix wrong enum value in nix-has-flakes
      7fbde25 Add tests for issue 157
      80b05d3 Fix docstring for new function
      acf4d6f Naming change
      acf6f9d Code style: change (+ 1 ...) to (1+ ...)
      87ba3a2 Fix $$ in string literals
      0950294 Fix out-of-bounds error
      7072348 Fix syntax highlighting for ''$ in indented strings
      bac8793 chore(deps): bump cachix/install-nix-action from 16 to 17
      bca3d51 chore(deps): bump actions/checkout from 2 to 3
      a237452 Add --print-build-logs to flake transient
      83980ca nix-mode: Add missing transient dependency for nix-flake
      5fb9df6 chore(deps): bump cachix/install-nix-action from 14.1 to 16
      c4abb64 nix-flake: Add a comment
      e167b82 nix-flake: Fix inconsistent state after switching the flake
      a3eb135 nix-flake: Fix miscomparison to avoid repeatedly adding to registry
      07b6069 nix-flake: Fix an unexpected error in assert
      c4e4f38 chore: Add nix-flake.el to Cask
      14f1bb2 chore: Bump install-nix-action to v14.1
      de85646 Add dependabot.yml
      [...]
    * =(220/428) nix-update-el: fc6c39c -> 1dd1434 [8 commit(s)]=
      055cb9a Don't specify ref in GitHub URLs
      ec573af Add an autoload directive to `nix-update-fetch`
      783fd4e Make GitHub URLs use `https://`
      a7d4bc0 Remove hardcoded reference to "refs/heads/master"
      7e7efc1 Allow specifying rev before fetching
      bf07f6a Require json
      a0e6728 Add support for fetchzip
      616b410 Add support for `fetchPypi`
    * =(221/428) org: 2b1b428 -> 4db67da [20757 commit(s)]=
      4db67da68 org.el: Improve automatic fast tag selection keys
      00adad935 org-src: Fix invisible text in src block fontification
      a303a794f Support interactive editing of comment blocks
      9cc60dee4 lisp/ob-plantuml.el: Insert results in buffer
      a0b21e3f1 * lisp/org.el (org-set-tags-command): Put local tags on top
      e47bcb021 lisp/ox-latex.el: `org-latex-language-alist' improved
      22eedaea8 lisp/ol.el: Fix some docstring style issues
      f71546cc9 * testing/lisp/test-ol.el: Fix test name
      3858a97ac * lisp/ol.el (org-insert-link): Fix edge case when ALL-PREFIXES is nil
      2bbb92a72 test-ol: tests for insert-description param when inserting links
      e3a05d09b ol.el: add description format parameter to org-link-parameters
      5a1b05031 org-colview: Do not rely on `current-column' ignoring display properties
      8f5bf1725 org-id-update-locations: Scan all the open Org buffers
      215de6176 Partially revert "org-mode: Make local variables effective during Org startup"
      4702a7303 org: Fix resource prompt in non-file buffers
      3626f0384 doc/org-manual.org: Fix typo in "The global TODO list"
      79dfb16d5 org-id: Fix `org-id-locations' variable name in error message
      fde93abb8 org-mode: Prevent early fontification
      5a49cc5f4 ox-latex: comment on \date LaTeX macro
      0599ddfd4 Revert "lisp/ox-latex: Omit empty date"
      [...]
    + =In repository "org-contrib", HEAD on default branch "master" has diverged from "origin/master"=

      1) Abort
      2) Merge "origin/master" into "master"
      3) Rebase "master" onto "origin/master"
      4) Reset "master" to "origin/master"
      5) Magit log "master...origin/master" and open recursive edit

      How to proceed? (1, 2, 3, 4, 5)     * (222/428) org-contrib: c1e0980 -> 39e2abc [2425 commit(s)]
      39e2abc [PATCH] Remove libraries that are in transition to be part of Org
      6f4ba83 [PATCH] Remove libraries that are in transition to other repositories
      c6aef31 lisp/org-contrib.el: Bump version to 0.4
      89ddcab *el: Fix Homepage keyword
      56fdeef README*: Update the list of files to delete from the next release
      3dd9841 Delete files
      15b03d5 * lisp/org-contacts.el: Update homepage
      e6cb6ca Replace removed `remove-if' by `cl-remove-if'
      4936783 lisp/org-eldoc.el: Fix inf-loop when point in org src blocks
      f237d67 lisp/org-eldoc.el: Whitespace change
      a33dd6f Rename some obsolete functions to their newer names
      5766ff1 Don’t assume Emacs internal timestamp format
      9dc8f49 Don’t assume Emacs internal timestamp format
      65821e4 Support numeric argument values in src definition lines
      e14dfea README*: Add org-contacts.el to the list of file to remove
      1ae5f90 org-contacts.el: Add the new homepage
      56a3bbb lisp/org-contrib.el: Bump version to 0.3
      23cd791 lisp/ol-man.el: Delete
      b8012e7 lisp/org-contrib.el: Bump version to 0.2
      f5edcb4 Move ob-stan.el here from Org's core
      [...]
    + =In repository "org-yt", remote "origin" has URL=
      "https://github.com/TobiasZawada/org-yt.git"
      but recipe specifies a URL of
      "https://github.com/thaenalpha/org-yt.git"

      1) Abort
      2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
      3) Rename remote "origin" manually, re-create it with correct URL, and fetch
      4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
      5) Delete remote "origin", re-create it with manually set URL, and fetch
    * =(234/428) gnuplot: 57be3c7 -> 803033e [6 commit(s)]=
      803033e Rename run-gnuplot to gnuplot-run
      e1d32b8 Remove variable gnuplot-ntemacs-p (internal)
      7bf8ffb Update URLs
      556aff7 Remove references to old Emacs version
      4b44969 Fix some documentation warnings in package-lint
      fca3877 Remove commented out function gnuplot-set-binding
    * =(240/428) org-re-reveal: f184e66 -> 6f78a0a [6 commit(s)]=
      6f78a0a Version 3.15.0
      5235df0 Add pointer on image resizing
      1a06363 Provide hints for multi-column layouts
      fb07995 Document changes
      5ca4834 Add test cases
      b107cc2 Refactor handling of slide attributes
    * =(241/428) reveal.js: 039972c -> e219184 [1 commit(s)]=
      e219184 update browserlist from '> 0.5%, IE 11, not dead' to '> 2%, not dead' #2985
    * =(242/428) org-roam: c386761 -> 7f453f3 [3 commit(s)]=
      7f453f3 (fix)promote: promote all metadata to file level (#2246)
      e435581 (fix): remove use of deprecated org-font-lock-ensure (#2238)
      917a325 (fix): links not displayed properly in org-roam-buffer (#2236)
    * =(246/428) ox-pandoc: 0a35d0f -> f8eac5e [6 commit(s)]=
      f8eac5e README note on required pandoc + org versions for citation support
      1beb7c0 Remove some application-specific formats from default export menu
      bf5d024 Make jira export functions autoload
      58a8373 Add export-to-jira for consistency
      453130c Add Jira (and Confluence) markdown export
      7a3a4b7 Avoid messing with the numbering of citation footnotes from CSL
    * =(249/428) php-mode: 81717a5 -> ca6ae67 [2 commit(s)]=
      52d96a8 Remove needless quote from choice values
      c143ab3 Use delq instead of cl-remove-if
    * =(251/428) phpunit.el: fe6bc91 -> 02020d4 [1 commit(s)]=
      ac57840 feat: Support Laravel stack trace format
    * =(255/428) emacs-async: 2f57dfa -> 6d164db [259 commit(s)]=
      5a6c0d5 Reset command-line-args-left (#154)
      7f4ed1e Add a (require 'bytecomp)
      676e500 Change customize :group to 'lisp
      14f48de Fix Makefile
      36a1015 Change default value of async-bytecomp-allowed-packages to 'all
      a1bd2ac untabify and indent-buffer
      fbbba03 fix package-lint/check-doc/byte-compiler warnings
      11769c1 Update version in source file as well
      e81c685 Update *pkg.el file
      64bb180 Fix typos
      c80976d Some rewording of part of README.md
      6577ae5 Add forge to async-bytecomp-allowed-packages
      67c3695 Fix async-bytecomp--get-package-deps according to
      5e353eb Change deps management in async-bytecomp.el
      bd68cc1 Handle dotted lists as well
      ec374ca Use consp instead of listp
      373b32a Remove props recursively when injecting vars with NOPROPS
      0b545da Only revert dired buffers if not remote
      4d3b737 Fix error from reverting to nonexistent directories
      d17c11e Add more info about emacs bug when using async
      [...]
    * =(258/428) anaconda-mode: cbea0fb -> 160e4e7 [1 commit(s)]=
      160e4e7 Pass in ssh port only if it exists
    * =(262/428) emacs-python-pytest: 5e72c34 -> 9bf8db3 [2 commit(s)]=
      9bf8db3 Switch to `compilation-mode' after pytest process finishes (#62)
      d031fa9 Add `0` as a valid argument that can be passed to `-n`. (#61)
    * =(268/428) rustic: 060149c -> baef1fa [1244 commit(s)]=
      76c3bdc cargo-comint-run: single run-args, no need for let*()
      8ee162c Reverted changes on rustic-cargo.el. Updated comint-run() run-args
      b94d936 Pass process-environment and exec-path through with-temp-buffer
      3b98e26 rustic-cargo-comint-run was causing a Lisp error - wrong-type-argument string, in rustic-cargo-run-get-relative-example-name()
      39029a7 fix readme
      f0f0391 Revert "disable automatic lsp setup"
      8770ab9 update lsp section in readme
      19513fe disable automatic lsp setup
      0bd7932 bump version to 3.2
      e90f0ca Fix typo.
      65efa87 Integrate cargo spellcheck with rustic
      0cee6a9 don't change eglot-ignored-server-capabilites
      207f614 Remove note from "Known issues" section
      4c831ac Add note to Installation section about rust-analyzer
      d363ace bump version
      352ef51 add notes about automatic lsp server installation
      5603dd2 add note for using make
      0da1159 don't require Cargo.toml for compile commands
      a9e445b Support custom cargo check/run/build/test commands
      66c6c83 rustic-doc: Note that windows is not supported.
      [...]
    * =(285/428) org-gcal.el: f8075bd -> 229463a [3 commit(s)]=
      d35e5aa Fix org-generic-id--last-update-id-time-put
      7b1ddd9 Intern strings for use as plist keys
      526ff41 org-generic-id-update-id-locations: don't scan unmodified files
    * =(288/428) alert: 7046393 -> fb92919 [81 commit(s)]=
      06197be Make alignment consistent
      46860bb Pass through user defined :persistent value
      208b817 Update documentaion with alternative
      2b1fe9e Fix issue #92
      761dd17 Make mode-line style work properly
      5c03dae formatting
      e4f7cdf Use the built-in AppleScript support of Emacs MacPort
      f47b0b3 Fix usage of alert-libnotify-additional-args
      d09c4c1 notifications: Add a default action to open corresponding buffer
      4a1823d Remove unnecessary dash
      9f329be Fix indetation
      46ce6ad Silence the byte compiler
      77163c1 Document cl-lib requirement in Package-Requires keywords
      847f008 Switch from cl to cl-lib and lexical binding
      afce117 Fix type definition of alert-notifications-priorities
      21a013c Ensure log4e logging is enabled when using default log4e functions
      b89172f Fix: libnotify: properly pass expire-time args to notify-send
      469285e Don't declare a variable at runtime that is never used
      5d80c5a Silence the byte compiler
      d01708b Add a variable to customize additional arguments to notify-send
      [...]
    * =(289/428) telega.el: 1080f10 -> 11c0c78 [3 commit(s)]=
      11c0c78 [enh] More i18n stuff
      a12beb6 [add] woozy-face emoji
      4da9c7a telega-msg-default-reaction is deprecated
    * =(290/428) emacs-everywhere: 0d0d185 -> a1b16b5 [2 commit(s)]=
      a1b16b5 Fix docstring typo
      cbe56e2 Reintroduce emacs-everywhere-major-mode-function
    * =(291/428) org-jira: 44fe1d9 -> 9362933 [5 commit(s)]=
      9362933 Fix old melpa URL reference
      7581ee2 Add test for a GET on an assigned issue (shows accountId, not name)
      1b0cfae Update "labels" fields on org-jira-update-issue call. Fix #305.
      97e9535 Format org-jira-refresh-issues-in-buffer-loose with default paren style
      05208a3 Added org-jira-refresh-issues-in-buffer-loose()
    * =(293/428) mastodon: 4ab5a4b -> 3ff8f25 [11 commit(s)]=
      3ff8f25 re-allow boost/fave of own toots!
      a74340a update discover bindings for profile followers/following
      04f7ff9 text-mode for update profile note
      b6184b5 bump version in boilerplate
      c06f1a1 --thread: use --api for get-json url for toot
      21358f5 refactor toggle boost and toggle fave
      ae945fd --thread: fetch current toot before printing thread
      95e20d6 --thread: fetch current toot before printing thread
      d0a9ced no fave counts for fol-req notifs
      04d35c7 tl--thread: FIX fetching of toot id for notifs/use parent toot
      8774ec3 --get-buffer-property: or rather than if
    * =(294/428) pocket-reader.el: 0a177d4 -> 88d1e60 [2 commit(s)]=
      88d1e60 Change: (pocket-reader-generic-add-link) Check clipboard
      2e08929 Tidy: Docstrings, compilation warnings
    + =In repository "elfeed-goodies", remote "origin" has URL=
      "https://github.com/algernon/elfeed-goodies.git"
      but recipe specifies a URL of
      "https://github.com/jeetelongname/elfeed-goodies.git"

      1) Abort
      2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
      3) Rename remote "origin" manually, re-create it with correct URL, and fetch
      4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
      5) Delete remote "origin", re-create it with manually set URL, and fetch
    * =(298/428) elfeed-org: d28c858 -> f8715f2 [1 commit(s)]=
      f8715f2 Fix Spacemacs link markdown (#74)
    * =(303/428) sql-indent: 6c5b352 -> f170a27 [1 commit(s)]=
      f170a27 Update sql-indent
    * =(307/428) copilot.el: 9b13478 -> 4a42da7 [3 commit(s)]=
      4a42da7 chore: update agent (copilot.vim 1.4.3)
      c164fe3 Raise error if there's an issue with node
      5b6f984 add: update config examples (#40)
    * =(310/428) .doom.d-2nd: 183bbca -> c5bed00 [1 commit(s)]=
      c5bed00 fix custom org-ql queries
    * =(313/428) dotfiles: 6622d0d -> 9e4467c [4 commit(s)]=
      9e4467c [Doom] update things
      253331e Enable :lang rust
      0d9b20a Revert "[Doom Alabaster] Less intense mu4e"
      872ba0a [Doom Alabaster] Less intense mu4e
    * =(315/428) devdocs.el: d5d0cfb -> 60099be [1 commit(s)]=
      60099be Bump version
    * =(319/428) org-roam-ui: 9474a25 -> c75fc75 [5 commit(s)]=
      a5b8119 ci: label issues from sponsors
      5b165e0 org-roam-ui--update-theme now uses org-roam-ui-custom-theme when set
      2cd93bf chore: build
      11111bb Read useInheritance from emacs config
      94b543c Making sure attachment preview works with file level ID
    * =(322/428) org-modern: 4131dd8 -> c82b50a [5 commit(s)]=
      c82b50a Fix org-modern-progress (Fix #82)
      f336d5a Fix loading on terminal Emacs (Fix #81)
      239c02a Update example
      9ad8b7e README update
      cef71f8 Improve todo statistic fontification
    * =(324/428) doct: 8464809 -> 15974ad [1 commit(s)]=
      15974ad doct--warn-template-entry-type-maybe: fix entry validation (#35)
    * =(328/428) bind-key was updated indirectly (with use-package)=
    * =(333/428) elisp-refs: 8f84280 -> af73739 [1 commit(s)]=
      728a79e Add open other window as in deadgrep
    * =(334/428) xref: cc312ec -> feb30d2 [1 commit(s)]=
      feb30d2 Update xref
    * =(335/428) svg-lib: 5ff87b7 -> 1e78346 [1 commit(s)]=
      1e78346 Update svg-lib
    * =(347/428) pcache: 893d2a6 -> 507230d [2 commit(s)]=
      a791e23 update emacs matrix
      2004af4 Convert to lexical scoping.
    * =(355/428) transient: a583d2b -> 3b26742 [18 commit(s)]=
      3b26742 transient--fit-window-to-buffer: Use correct package prefix
      a5562cb manual: Avoid texinfo complications
      47ebcee manual: Fix minor defects
      2a47c32 manual: Include GPLv3 in appendix
      69584bf manual: Use @insertcopying
      1b42da2 manual: Update copyright notice
      eba78cb manual: Use more precise @dircategory
      1be2b72 manual: Use verbatim instead of code in diagram legends
      9cd69ef manual: Use double quotation marks (U+201C and U+201D)
      3ff531b manual: Use "verbatim" emphasis markers
      bcd9fbe manual: Use new "dfn" macro
      b49e79d manual: Use new "codevar" macro
      86b24eb manual: Use new "kbdvar" macro
      5d116c7 manual: Use new "var" macro
      2c7624e manual: Use "kbd" macro explicitly
      389d2bf Backport changes from Emacs
      d855bbf Fix typo in changelog
      cc887eb transient--delay-post-command: Fix execute-extended-command handling
    * =(357/428) magit-section was updated indirectly (with magit)=
    * =(359/428) git-gutter: a50672b -> 315e792 [11 commit(s)]=
      7f80640 Update test.yml
      180fd92 fix ci badge
      5acc82d update badge link
      ec446f5 package before install
      84d0fb7 ignore
      9a298de add fail fast
      5f687d8 fix eask command
      f0b9f44 simplify
      5301d54 fix meta
      3082b77 feat(Eask): Replace Cask with Eask
      ab85e2c Fix a typo in README
    * =(363/428) expand-region.el: 7e5bbe2 -> c5c4362 [1 commit(s)]=
      c5c4362 Fix wrong type argument on Emacs 28.1
    * =(367/428) emacs-language-id: cbd5b8f -> 1d05bb7 [6 commit(s)]=
      1d05bb7 Fix mint-mode order issue.
      6ca0c79 Recognize Mint in mint-mode
      e48aba3 Recognize ERB templates in web-mode
      e7f743e Move languages.{sh,yml} to admin/
      77e6b21 Add languages.sh
      3dcf792 Update .gitignore
    * =(379/428) gh.el: 27ccc89 -> 9c47468 [1 commit(s)]=
      59d8728 update emacs matrix
    * =(381/428) marshal.el: 490496d -> bc00044 [1 commit(s)]=
      e77a3ae update emacs matrix
    * =(387/428) yaml.el: cb1cc42 -> 73fde9d [10 commit(s)]=
      4a3243a yaml--the-end: fix incorrect regexp
      af49540 Use cl-defun &key to allow eldoc argument hints to work better
      ee34639 Update docstring and README to match current behavior
      94ea32e version bump
      7783d80 Don't remove all properties, just yaml-n
      7ef2e8c fix unit tests
      fdc6592 fix zero-column indent problems; add more unit tests
      c3988d1 store current indent level and use that for basis of block indent
      67e8b5f Fix off-by-one bug for storing position
      419e85f fix folding block parsing error
    * =(398/428) js2-mode: 88c081e -> 841cfec [3 commit(s)]=
      841cfec Bump the version
      6b83e24 Fix #591 by saving the position earlier
      7c43ea5 Add support for the d (hasIndices) and s (dotAll) regexp flags
    * =(404/428) pythonic: fe75bc1 -> c18a5bd [1 commit(s)]=
      c18a5bd Deactivate virualenv when python-activate is calles with nil
    * =(407/428) rust-mode: 56e5c3a -> 01ba441 [2 commit(s)]=
      01ba441 add deprecation note for racer and rls
      7bff488 bump version to 1.0.5
    * =(419/428) hierarchy: fed505b -> d8373b3 [1 commit(s)]=
      63bd723 Fix and link version information in Readme
    * =(427/428) jsonrpc: efb4187 -> 2c74dc5 [1 commit(s)]=
      2c74dc5 Update jsonrpc
    * =Updated 123 package(s)=
    + (Re)building packages...
      > Building straight...
      > Building use-package...
      > Building use-package > Building bind-key...
      > Building use-package...
      > Building all-the-icons...
      > Building dtrt-indent...
      > Building helpful...
      > Building helpful > Building elisp-refs...
      > Building helpful...
      > Building smartparens...
      > Building projectile...
      > Building project...
      > Building project > Building xref...
      > Building project...
      > Building corfu...
      > Building svg-lib...
      > Building cape...
      > Building company...
      > Building vertico...
      > Building consult...
      > Building consult > Building compat...
      > Building consult...
      > Building consult-dir...
      > Building flycheck...
      > Building embark...
      > Building embark-consult...
      > Building marginalia...
      > Building doom-themes...
      > Building nav-flash...
      > Building pcache...
      > Building doom-modeline...
      > Building evil...
      > Building treemacs...
      > Building treemacs-evil...
      > Building treemacs-projectile...
      > Building treemacs-magit...
      > Building treemacs-magit > Building magit...
      > Building treemacs-magit > Building magit > Building git-commit...
      > Building treemacs-magit > Building magit > Building git-commit > Building transient...
      > Building treemacs-magit > Building magit > Building git-commit...
      > Building treemacs-magit > Building magit > Building magit-section...
      > Building treemacs-magit > Building magit...
      > Building treemacs-magit...
      > Building treemacs-persp...
      > Building lsp-mode...
      > Building lsp-mode > Building markdown-mode...
      > Building lsp-mode...
      > Building git-gutter...
      > Building writeroom-mode...
      > Building expand-region...
      > Building evil-lion...
      > Building evil-nerd-commenter...
      > Building evil-numbers...
      > Building evil-collection...
      > Building ts-fold...
      > Building format-all...
      > Building format-all > Building language-id...
      > Building format-all...
      > Building doom-snippets...
      > Building dired-rsync...
      > Building dirvish...
      > Building info-colors...
      > Building flycheck-posframe...
      > Building spell-fu...
      > Building citar...
      > Building citar > Building parsebib...
      > Building citar > Building org...
      > Building citar > Building citeproc...
      > Building citar...
      > Building citar-embark...
      > Building howdoyou...
      > Building realgud...
      > Building dap-mode...
      > Building dap-mode > Cloning lsp-docker...
      > Building dap-mode > Building lsp-docker...
      > Building dap-mode > Building lsp-docker > Building yaml...
      > Building dap-mode > Building lsp-docker...
      > Building dap-mode...
      > Building docker...
      > Building dockerfile-mode...
      > Building fzf...
      > Building gh...
      > Building gh > Building marshal...
      > Building gh...
      > Building dumb-jump...
      > Building async...
      > Building osx-dictionary...
      > Building lsp-ui...
      > Building lsp-bridge...
      > Building code-review...
      > Building pdf-tools...
      > Building kurecolor...
      > Building evil-textobj-tree-sitter...
      > Building evil-terminal-cursor-changer...
      > Building paredit...
      > Building clojure-mode...
      > Building clj-refactor...
      > Building clj-refactor > Building cider...
      > Building clj-refactor...
      > Building elisp-def...
      > Building elisp-demos...
      > Building buttercup...
      > Building graphql-mode...
      > Building js2-mode...
      > Building typescript-mode...
      > Building tide...
      > Building lua-mode...
      > Building nix-mode...
      > Building nix-update...
      > Building org-contrib...
      > Building gnuplot...
      > Building alert...
      > Building org-re-reveal...
      > Building revealjs...
      > Building org-roam...
      > Building ox-pandoc...
      > Building php-mode...
      > Building phpunit...
      > Building anaconda-mode...
      > Building anaconda-mode > Building pythonic...
      > Building anaconda-mode...
      > Building python-pytest...
      > Building rustic...
      > Building rustic > Building rust-mode...
      > Building rustic...
      > Building org-gcal...
      > Building telega...
      > Building emacs-everywhere...
      > Building org-jira...
      > Building mastodon...
      > Building pocket-reader...
      > Building md4rd...
      > Building md4rd > Building hierarchy...
      > Building md4rd...
      > Building elfeed-org...
      > Building sql-indent...
      > Building copilot...
      > Building copilot > Building jsonrpc...
      > Building copilot...
      > Building minibuffer-header...
      > Building aj-dark+-theme...
      > Building agraul-doom-themes...
      > Building devdocs...
      > Building org-roam-ui...
      > Building org-modern...
      > Building doct...
      * Rebuilt 127 package(s)
  + Purging orphaned packages (for the emperor)...
    - No builds to purge
    + Purging ELPA packages...
      * Deleted archives
      * Deleted gpg
    + Purging straight repositories...
      * Purged repos/doom-emacs-private
      * Purged repos/font-utils
      * Purged repos/unicode-fonts
    + Regrafting 410 repos...
      * Finished regrafting. Size before: 0.0KB and after: 0.0KB (0.0KB)
    - No ELN directories to purge
  + (Re)generating autoloads file...
    + Generating autoloads file...
    + Byte-compiling autoloads file...
    * Generated .local/autoloads.28.1.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
 * Finished upgrading Doom Emacs
 * Finished in 42m 44s
#<process nyan-music>
** <2022-11-01 Tue>
! No profile loader found. Generating one...
  > Regenerating it...
  > Synchronizing 1 known profile...
    - Added safe-mode
    ✓ Regenerated profile loader: ~/.config/emacs/profiles/load.el
> Tangling your literate config...
  ✓ Done tangling 42 file(s)!
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Installing packages...
    > Building visual-fill-column...
    x There was an unexpected runtime error
      Message: Invalid sub-list head in :files directive: :not
      Backtrace:
        (error "Invalid sub-list head in :files directive: %S" :not)
        (if (stringp (car spec)) nil (error "Invalid sub-list head in :files...
        (cond ((eq spec :defaults) (setq files (append straight-default-file...
        (let ((spec (car files))) (setq files (cdr files)) (cond ((eq spec :...
        (while files (let ((spec (car files))) (setq files (cdr files)) (con...
        (let ((mappings nil) (exclusions nil)) (while files (let ((spec (car...
        (straight--expand-files-directive-internal (:defaults (:not "Cask" "...
        (let* ((default-directory src-dir) (result (straight--expand-files-d...
        (straight-expand-files-directive (:defaults (:not "Cask" "LICENSE" "...
        (let ((--dolist-tail-- (straight-expand-files-directive files (strai...
        (progn (let ((dir (straight--build-dir package))) (if (file-exists-p...
        (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-re...
      ! Wrote extended backtrace to ~/.config/emacs/.local/logs/cli.doom.221101042145.68921.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
    ✓ Finished in 10.70771s
#+begin_src shell :async t
rm -rf ~/.config/emacs/.local/straight/repos/straight.el
cd ~/.config/emacs
git pull
doom clean  # in case you've byte-compiled
doom sync -up!j 8
#+end_src
> Installing straight...
> Tangling your literate config...
  ✓ Done tangling 42 file(s)!
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Installing packages...
    > Building visual-fill-column...
    > Building spell-fu...
    > Updating recipe repos...
      ✓ melpa updated (ec8e444 -> e3da6cf)
        - $ cd /Users/nopan/.config/emacs/.local/straight/repos/melpa/
          $ git config --get remote.origin.url
        
          https://github.com/melpa/melpa.git
        
          [Return code: 0]
        
          $ cd /Users/nopan/.config/emacs/.local/straight/repos/melpa/
          $ git fetch origin
        
          From https://github.com/melpa/melpa
             ec8e4440..e3da6cf0  master     -> origin/master
      ✓ gnu-elpa-mirror updated (ff81342 -> a4f8d64)
        - $ cd /Users/nopan/.config/emacs/.local/straight/repos/gnu-elpa-mirror/
          $ git config --get remote.origin.url
        
          https://github.com/emacs-straight/gnu-elpa-mirror.git
        
          [Return code: 0]
        
          $ cd /Users/nopan/.config/emacs/.local/straight/repos/gnu-elpa-mirror/
          $ git fetch origin
        
          From https://github.com/emacs-straight/gnu-elpa-mirror
             ff81342..a4f8d64  master     -> origin/master
      ✓ el-get updated (39f494a -> 0a9d568)
        - $ cd /Users/nopan/.config/emacs/.local/straight/repos/el-get/
          $ git config --get remote.origin.url
        
          https://github.com/dimitri/el-get.git
        
          [Return code: 0]
        
          $ cd /Users/nopan/.config/emacs/.local/straight/repos/el-get/
          $ git fetch origin
        
          From https://github.com/dimitri/el-get
             39f494a..0a9d568  master     -> origin/master
      ✓ emacsmirror-mirror updated (d6b92f1 -> be9d095)
        - $ cd /Users/nopan/.config/emacs/.local/straight/repos/emacsmirror-mirror/
          $ git config --get remote.origin.url
        
          https://github.com/emacs-straight/emacsmirror-mirror.git
        
          [Return code: 0]
        
          $ cd /Users/nopan/.config/emacs/.local/straight/repos/emacsmirror-mirror/
          $ git fetch origin
        
          From https://github.com/emacs-straight/emacsmirror-mirror
             d6b92f1..be9d095  master     -> origin/master
    > Cloning citar-org-roam...
    > Building citar-org-roam...
    > Cloning org-mac-link...
    > Building org-mac-link...
    > Cloning ob-clojure-literate.el...
    > Building ob-clojure-literate...
    > Cloning ob-php...
    > Building ob-php...
    ✓ Installed 6 packages
  > (Re)building packages...
    > Building git-timemachine...
    ✓ Rebuilt 1 package(s)
  > Updating packages (this may take a while)...
    ✓ (6/433) use-package: 0ad5d9d -> 0be480e [706 commit(s)]
        2dd93e0 fix #1008: allow passing the SPEC-TYPE argument via :custom-face
        c81f9e7 Bump version to 2.4.3
        4932ed2 bind-key.el: Bump version for ELPA
        cdd59d5 Add README.org to explain purpose of doc/ directory
        7b05028 Update version to 2.4.2
        e6932fe Add .elpaignore
        057e25c Update copyright for submission to ELPA
        4fdc36a fix #934: use face-spec-set instead of custom-set-faces
        ba9007c Update CI and Makefile to fail on compiler warnings
        b749cef Fix emacs native compilation warning for bind-key
        b8ac02f Fix emacs native compilation warning
        e2d173b Revert "Remove use-package-font-lock-keywords"
        e1a08c5 Go back to making `override-global-mode` non-global
        cdec032 Correct badge URL
        b635f58 Make sure that bind-key's `override-global-mode` is initially on
        b9400ec Quote single quotes in docstrings or use different quoting
        17056cc gitignore: Ignore more generated documentation and stats
        66834ff manual: Regenerate texi file
        b185c6b manual: Copy text from Introduction to info entry page
        df8cc6b manual: Downcase src and example keywords
        [...]
    ✓ (11/433) all-the-icons.el: b18db6b -> 4a4d626 [3 commit(s)]
        15b77955 added support for meson
        6f876fa1 alphabetical order
        3a82045c added support for odin
    ✓ (18/433) helpful: 94a07d4 -> 6633d82 [2 commit(s)]
        6633d82 Assign `list-buffers-directory` to help topic
        cb9beb0 Unescape \= in signature docstring
    ✓ (22/433) projectile: dc6e7ff -> 20aa2ad [6 commit(s)]
        20aa2ad Support `projectile-replace` to select file extension on C-u (#1778)
        99b5f69 Tweak wording
        26be837 [Docs] Tweak some wording (#1793)
        9427361 Add src-dir and test-dir Properties to mill Project Type (#1790)
        c191195 Fix doc errors on Emacs snapshot
        d811e2b Add a progress reporter to recursive progress discovery
    ✓ (25/433) emacs-which-key: 1ab1d0c -> 8093644 [11 commit(s)]
        2875fcd Ignore .DS_Store
        e993113 Allow truncating without using any ellipsis
        08d57fe Don't make description longer than allowed when truncating
        783d695 Support different types for which-key-max-description-length
        fe68fe2 Avoid unnecessary work
        245be33 Fix vertical off-by-one error
        5fe2d33 Fix horizontal off-by-one error
        254d6fd Don't pad beyond maximal width
        16c992f Displaying just one column means pages are arranged vertically
        d924a4a Calculate format string only once
        55b2440 Replace or quote certain single quotes in docstrings
    ✓ (28/433) emacsql: 373975c -> e318a6c [39 commit(s)]
        e318a6c Add new SQLite back-ends
        67ca812 make: Suppress warning about obsolete autoload package
        ec4f3d0 Resume development
        c1a4407 Release version 3.1.1
        bfbd0c3 Resume development
        40c41d0 Release version 3.1.0
        4fe4413 Re-indent some data so that machine and human can agree
        1becb00 Define a few constants as such
        b907279 Fix docstring of emacsql-sqlite-condition-alist
        20cdad6 Include sqlite error code in error data
        0da3f06 Fix docstring typo
        5c4aa10 Do not warn about missing pg functions
        50b1394 make: Fix compiling and cleaning tests
        9ee397b Whitespace cosmetics
        5818000 make: Update pg repository url
        a4d01ed Adjust emacsql-pg to new pg version from original author
        b4d5ef4 make: Don't require pg.el to be available to build and test
        d3d76ea make: Use essentially same Makefile as for other packages I maintain
        b405d99 make: Don't use LDFLAGS to set Emacs load-path
        b9d848f make: Don't warn about implicit fallthroughs
        [...]
    > In repository "copilot.el", HEAD on default branch "main" has diverged from "origin/main"

         1) Abort
         2) Merge "origin/main" into "main"
         3) Rebase "main" onto "origin/main"
         4) Reset "main" to "origin/main"
         5) Magit log "main...origin/main" and open recursive edit

      How to proceed? (1, 2, 3, 4, 5)
     ✓ (31/433) copilot.el: 4a42da7 -> 3b78e9b [99 commit(s)]
        3b78e9b fix: allow complete in non-file buffers (#57)
        0d1b171 add: proxy support
        26f6a5c Copilot.vim 1.6.0
        17348d0 Copilot.vim 1.5.4
        f316299 Update spacemacs documentation (#56)
        b1ace0a add: documentation for copilot-clear-overlay-ignore-commands
        d3f6d40 add: support a list of commands that should be allowed to call without clearing the copilot overlay
        826995c Copilot.vim 1.5.3
        109a3d8 Copilot.vim 1.5.2
        511440d Copilot.vim 1.5.1
        3925041 ci: set return code to 0
        542b7b3 fix: completion cycling should keeps the overlay
        eeafc98 Copilot.vim 1.5.0
        5a14dd7 ci: auto update copilot binaries
        21ee307 copilot--overlay: reuse when possible
        920e37a copilot-mode: add/remove hooks properly
        1b1b0f5 chore: update agent (copilot.vim 1.4.3)
        e549d82 Raise error if there's an issue with node
        c7d29f7 add: update config examples (#40)
        2fd740c add: a global mode and a keymap for the completion overlay (#31)
        [...]
    ✓ (32/433) minibuffer-header: fe5d90d -> 5b5ffd9 [1 commit(s)]
        dcdbaeb feat(src): add autoload
    ✓ (34/433) mentor: a820c84 -> 88ef7de [38 commit(s)]
        88ef7de Fix typo in README
        291ba7f Rename functions for namespacing
        1481f81 Clean up mentor-trackers.el, and add new binds/commands
        f9c4a52 Change files to trackers
        cc51ee5 Add mentor-tracker-mode to view torrents tracker information
        89548f9 Improve README section on installing
        bd51a02 Simplify description of libxml issue
        218579c Require subr-x when compiling
        0382dc2 Harden GitHub CI workflow
        f027f6e Fix GitHub CI workflow
        089df9b Add missing "/" to gnu.org URL
        b8dfa8f Make test run check-declare
        75faf58 Add test.yml
        0ca84af Require url-scgi 0.8
        480602f Bump version to 0.5
        8f74039 Ignore backup files
        cddddfc Delete bundled url-scgi.el
        b08697d Add url-scgi to Package-Requires
        ba02a36 Add .elpaignore for NonGNU ELPA
        300dd08 Don't byte-compile .dir-locals.el
        [...]
    ✓ (39/433) dotfiles: 9e4467c -> bd59132 [15 commit(s)]
        bd59132 [Doom] Add more GTD contexts
        335d02f [Doom] Make org-link-bugzilla URL-aware
        78e1ed7 [Doom] Don't use a file-template for Python
        b66f05d [Doom] avy keys + no org-modern-todo
        9e2c232 [Doom] Fix org-agenda-custom-commands order
        1f3c2e3 [Doom] Simplify interaction with org-agenda
        f943824 [Doom] Refactor setting org-agenda-custom-commands
        71832f9 [Doom] org: hide emphasis markers
        d873c5e [Doom] Don't maximize in launch
        55de0b5 [Doom] Use Alabaster Theme from its own repo
        ea0c1f8 [Doom] Update init.el
        bcefd2c [Doom] Try org-modern instead of +pretty
        d29998a [Doom] Stop using deprecated Doom things
        0f1e38b [Doom] font: Iosevka SS05 Light Extended
        fe33a8d [Doom Alabaster] Align tree-sitter faces
    ✓ (41/433) devdocs.el: 60099be -> 61ce83b [1 commit(s)]
        61ce83b New user option devdocs-window-select
    ✓ (43/433) emacs-clj-deps-new: 183089e -> e1cf65e [1 commit(s)]
        e1cf65e autoload user facing function
    ✓ (44/433) orca: 47c03af -> 0687f41 [1 commit(s)]
        0687f41 orca.el : Fix undeclared dependencies.
    ✓ (45/433) org-roam-ui: c75fc75 -> 6bf6a5e [8 commit(s)]
        6bf6a5e chore: build
        1936250 fix: type-error
        3f28da8 docs: add docs about add-node-to-local-graph
        c4a9897 feat: add/remove note to local graph from emacs
        fb26ac0 fix: small bugs
        a575d14 fix: move a ton of functions to separate files
        fa84c05 comment out useless usestate
        16a8da9 Update FUNDING.yml
    ✓ (47/433) org-appear: 60ba267 -> eb9f9db [1 commit(s)]
        eb9f9db Document Org variables that should be set to hide elements (#51)
    ✓ (48/433) org-modern: c82b50a -> 59b2e3c [32 commit(s)]
        59b2e3c Adding string support for org-modern heading hide star
        8bf1023 Use logand
        ed9d67d Version 0.5
        adf89bc Update links
        828cf10 face is already removed by font-lock-default-unfontify-region
        246fb4c Better unfontify
        44bb8bb Ensure that org-modern doesn't change modification status (Fix #95)
        5c4daa2 Update agenda on theme change
        d6307ee Support theme switching
        34ccd3a Simplify table scaling
        610e6fb Avoid advice, instead replace unfontify-region-function
        e086f14 Use better mechanism to adjust font-lock-keywords
        ffb2758 example: Add test from #33
        9e60fa6 Ensure that source blocks are properly fontified (Fix #33)
        df19969 org-modern--update-label-face: Simplify
        fb0ec9c org-modern-label: Expand docstring, warn about overriding the face
        536c82b Refactoring and simplification
        7a1e15c Add missing check
        148eedb Remove org-modern-variable-pitch
        9e76abd Table scaling (See #69 and #75)
        [...]
    ✓ (49/433) org-transclusion: d765810 -> 1b2dae2 [2 commit(s)]
        1b2dae2 Update org-transclusion
        b00a053 Update org-transclusion
    ✓ (50/433) doct: 15974ad -> 506c22f [1 commit(s)]
        506c22f doct-unload-function: fix format specifier
    ✓ (51/433) org-web-tools: b94a07a -> b5b7fee [1 commit(s)]
        b5b7fee Docs: Remove image
    ✓ (53/433) org-edit-indirect.el: f146d1b -> 62894ac [1 commit(s)]
        62894ac adds drawers and fixes headlines
    ✓ (54/433) lsp-tailwindcss: 09377d5 -> c0ca58d [3 commit(s)]
        c0ca58d feat: bump server version to 0.8.7
        a641718 feat: autoload functions and make check server (#45)
        6cff719 add a helper function to check server version
    ✓ (55/433) corfu: f0d1f1d -> 03688d6 [8 commit(s)]
    ✓ (56/433) orderless: 8b9af27 -> b355ef6 [166 commit(s)]
        531372b Name advice function, link to u/hvis's comment
        6b86527 Flex matching: more efficient regexp, better highlighting
        c06e66d Avoid long lines
        b341b82 Update README regarding Prescient (Fix #121)
        684c5e4 Improve orderless-try-completion (Fix #118)
        fbf969e Add note about custom styles for `company-capf'
        2646dad Update manual to mention Vertico
        cbb1c00 Mention orderless works fine with Vertico (fix #59)
        f7be0fb Make strict initialism independent of syntax tables (fix #60)
        871eb1d Use add-face-text-property
        e4c38ef README: Add variable category to orderless+initialism sample
        94e8940 Omit null components (fix #55)
        d2891b8 orderless+initialism example requires Marginalia (see #54)
        d13f47d Bump version number
        8d187bd Only enable regexp and literal matching styles by default
        05fc3d2 fix typo
        818af9e Remove pattern compiler variable
        44935d8 Fix bug when all matching styles return nil
        e5cb3f7 update readme
        f6394f1 orderless-default-pattern-compiler: Ignore nil components
        [...]
    ✓ (57/433) kind-icon: cce18f7 -> 8adc665 [2 commit(s)]
    ✓ (58/433) cape: ab2f4ec -> df9067c [12 commit(s)]
        df9067c Minor cleanup
        7575584 Fix `cape-history` for Eshell and Comint. (#64)
        b98c2ea cape-symbol-wrapper: Add rst-mode
        e8b6a8a Improve cape--symbol-annotation
        caa5500 Add cape-symbol-wrapper and cape--symbol-exit
        c976301 Fix mode aliases in cape-keyword (Fix #63)
        89fe409 Update links
        5cd6b86 Version 0.9
        3ccb3bb Avoid setf
        0361400 Fix #60 - Use /usr/share/dict/words
        f360464 cape-keyword: Add erlang-mode
        f632114 cape-keyword: Add crystal keywords
    ✓ (60/433) company-mode: f1877a3 -> 48fea7a [6 commit(s)]
        48fea7a Fix new byte-compilation warning
        5d3fa6d Pacify Emacs 29 compiler warnings
        5b14107 add erlang-mode keywords
        77ceda0 User manual: fix F1 key typo
        cfc759a Add Crystal-mode into company-keywords
        cab10c0 Adjust recently added docs
    ✓ (62/433) vertico: a2e9b1b -> bfdc174 [23 commit(s)]
        bfdc174 vertico-directory: Fix typo
        8735749 Add missing completion-predicate
        3106094 Version 0.28
        cb174fc Revert "vertico-exit: Allow null completion only if explicitly requested"
        439c971 Revert "Accept empty input if minibuffer-default is non-nil"
        26669c6 vertico-repeat--restore: Use vertico--update to update state
        0baa4c2 Update naming convention
        fedcee0 Rename function, shorter name
        604727b Ensure that Vertico is always initialized fully (Fix #289)
        f587c13 Formatting
        ae58e7a Remove vertico-directory--completing-file-p
        e76f30f Rename functions, they update the entire state
        5023833 Update readme
        30dad48 README update
        49016ba Update links
        8078b8c Move vertico--index computation to vertico--recompute-candidates
        54c8f73 vertico-insert: Always insert first candidate, if prompt is selected
        ebe8a38 Code readability
        f6171a7 Do not try to resize root window (Fix #279)
        64b57b0 Version 0.27
        [...]
    ✓ (63/433) consult: e4546ed -> 3226c1a [58 commit(s)]
        3226c1a Expand docstring of consult-customize
        a337cbc Update changelog
        51402e8 README update
        00a58f5 README: Update recommended preview configuration
        5b258a5 Remove obsolete consult-line-point-placement
        82a41d3 Formatting
        8fac54c consult--jump-1: Fix case, where current-buffer/=window-buffer
        b27ea3e Indentation
        0abeee7 Add consult--source-file-register
        cf9c5e5 Update commentary
        d5b3286 Version 0.20
        cc615b0 Update changelog
        428ffd0 Minor cleanup
        cb5aea3 Enable setting an index var from consult-mode-histories (#669)
        6cb8cd8 Revert "Enable setting an index var from consult-mode-histories (#669)"
        e5333d0 Revert "Fix whitespace"
        1b6d22d Fix whitespace
        3b399ab Enable setting an index var from consult-mode-histories (#669)
        8717aa2 Refactor consult--find-file-temporarily
        7c3ee6e typo (#664)
        [...]
    ✓ (64/433) compat: d8967c0 -> 056e3cc [8 commit(s)]
    ✓ (65/433) consult-dir: 8abf62d -> ed8f087 [1 commit(s)]
        ed8f087 dont open connections to remote hosts from recentf (#22)
    ✓ (66/433) consult-flycheck: 9b40f13 -> 1d43437 [1 commit(s)]
        1d43437 Remove consult--jump-state argument (#1)
    ✓ (67/433) embark: 5d0459d -> 3a86e4b [26 commit(s)]
        3a86e4b Delete FUNDING.yml file
        4af269d Add autoload for org-attach-dir
        99e6dbf embark-org: transform org attachment link to org-file-link
        1bacf0b Create FUNDING.yml
        4ce430c Correct loading instructions for embark-consult
        9b23155 Move warning
        97f986b Update info manual after change in #550
        52b25d9 Remove some obsolete variables
        e565f91 Update commentary
        3b91887 Add a warning in case embark-consult cannot be loaded
        eaa5f5d Use vertico--update
        2422d4e Fix wikipedia link example code (fix #545)
        6b28976 Silence compiler
        4f924a0 Update info manual for the #516 fix
        11129db Fix #516
        8c768f2 embark-insert: leave point after inserted text (fix #533)
        fc9f138 Set next-error-last-buffer in grep export (fix #537)
        8461bdc embark-toggle-variable: Toggle local variable
        28c1e33 Change bindings for Org link copying
        476f2ae Fix bugs found in PR #542
        [...]
    ✓ (68/433) embark-consult was updated indirectly (with embark)
    ✓ (69/433) marginalia: 69442c2 -> c9297ee [12 commit(s)]
        c9297ee Add @oantolin to FUNDING.yml
        cc7a086 Version 0.15
        5108586 Remove unnecessary defvar
        d13ea27 Update docstring
        459f230 marginalia-annotate-package: Handle multiple installed package versions
        606dc0a Update links
        c37a276 Drop Selectrum-specific workaround to obtain the full candidate
        ddba3a3 Improve tab annotator
        7f5bf78 marginalia-annotate-tab: Additionally show tab group (Fix #147)
        db12d80 marginalia--cache-reset: Ignore arguments
        b6d9a7e Version 0.14
        fd66a02 Minor README cleanup
    ✓ (71/433) all-the-icons-completion: 286e2c0 -> 4d8ae54 [2 commit(s)]
        4d8ae54 autoload bookmark-get-filename
        fc90b56 add icons for bookmark
    ✓ (72/433) vertico-posframe: 7ca364d -> 46aa1df [1 commit(s)]
        46aa1df :group 'vertico-posframe => :group 'vertico, fix #17
    ✓ (74/433) themes: aa13e7f -> 535800f [5 commit(s)]
        535800f feat(base): add symbol-overlay faces
        2880aab fix(ext-treemacs): add icon for pom.xml
        c4e92a7 tweak(vibrant): use more vivid color for variables
        3e68f63 dev: update .doomrc
        aff98a6 fix: invalid nil values in Emacs 29
    ✓ (78/433) hl-todo: 2337eac -> 8dbe52b [2 commit(s)]
        8dbe52b make: Suppress warning about obsolete autoload package
        c699c9b hl-todo--setup: Make sure lambda is code not data
    ✓ (79/433) hydra: 9e9e00c -> 317e1de [1 commit(s)]
        317e1de Fix emacs native compilation warning
    ✓ (81/433) doom-modeline: 1b74638 -> b66d5e5 [51 commit(s)]
        b66d5e5 Support helm-ag.
        5c98267 Use unspecified instead of nil in `defface'
        936bfbc New option: doom-modeline-modal.
        0993f4b Remove extra spaces in buffer name.
        8cad541 Remove extra space after buffer name.
        68689f4 Ensure bar height is fixed.
        997c324 Update the buffer name when the current Info node changes
        66369c2 Fix: display incorrect mode-line for info.
        36cde4c [Feature] Status indicator for active compilation buffer.
        1d6ad06 Fix #578: Wrong buffer name being displayed.
        5dbb434 Fix: refresh font width cache in 29.
        d39de4d Minor fix.
        b1fa665 Align right segment for font size of mode-line.
        eb27003 Remove after-revert-hook since find-file-hook has been called in revert-buffer.
        657ff0a Fix #576: Bad face in some buffer names.
        e2c062e Update buffer info after reverting buffer.
        deca7ae Refactor.
        13748fe [Feature] Define calculator mode-line.
        aa0e2dd Change eglot--major-mode to eglot-major-modes.
        df15169 Update FAQ.
        [...]
    ✓ (83/433) evil-anzu: d3f6ed4 -> d1e98ee [1 commit(s)]
        a964de4 Fix emacs native compilation warning
    > In repository "treemacs", HEAD on default branch "master" has diverged from "origin/master"

         1) Abort
         2) Merge "origin/master" into "master"
         3) Rebase "master" onto "origin/master"
         4) Reset "master" to "origin/master"
         5) Magit log "master...origin/master" and open recursive edit

      How to proceed? (1, 2, 3, 4, 5)     ✓ (87/433) treemacs: aa3f454 -> 984099b [55 commit(s)]
        984099b [Misc] Fix typo.
        75ba10f [Rendering] Don't load obsolete extensions module.
        19eb68e [Mu4e] Use new initialization syntax.
        0408fc1 [Annotations] Remove obsolete variable.
        76807be [Misc] Fix compile issues for latest Emacs build.
        d508822 [Misc] Don't use buffer-local-value as a generalised variable.
        180989a [Docs] Add peek-mode documentation.
        12e0393 [Build] Add build for Emacs 28.2.
        056e5a4 [Build] Fix treemacs--parent tests.
        5a26f45 [Misc] Fix typo.
        40e0bde [Interface] fix copy-functions used `kill-new` not work in emacs-29
        20765ac [Treelib] Implement depth-based expansion for extensions.
        e4bb236 [Treelib] Fix updates of variadic parent nodes.
        13a8a06 [Magit] Take extension nodes into account when running updates.
        b4bb1d7 [Treelib] Implement prefix-arg based expansion depth.
        e4a9cce [Treelib] Correct :path property of variadic nodes.
        78fdc88 [Treelib] Add missing :leaf property.
        7c853db [Treelib] Remove :face argument.
        6dc0ca1 [Treelib] Make the :face parameter optional.
        59b1fc2 [Project-Following] Ensure project is followed at startup.
        [...]
    ✓ (88/433) treemacs-evil was updated indirectly (with treemacs)
    ✓ (89/433) treemacs-projectile was updated indirectly (with treemacs)
    ✓ (90/433) treemacs-magit was updated indirectly (with treemacs)
    ✓ (91/433) treemacs-persp was updated indirectly (with treemacs)
    ✓ (92/433) lsp-treemacs: 9859326 -> 2894e6d [5 commit(s)]
        2894e6d Delete redundant code
        6cfffec Fix lsp-treemacs to work with latest treemacs
        f7ae975 Disable expanding of the tree
        0502bf1 Move initialization in treemacs-initialize
        e668656 Fix lsp-treemacs to work against latest treemacs
    ✓ (95/433) ace-window: 0577c42 -> 77115af [7 commit(s)]
        77115af Get inherited faces in posframe.
        3fe3534 Make posframe buffers hidden
        0d9a89e ace-window-posframe.el (ace-window-posframe-disable): Fixup
        aec8fd6 ace-window-posframe.el: map -> cl-map
        e3e6ec1 Fix slowness of posframe
        751bd32 Allow configuration of the posframe position
        b2cc22a Provide ace-window-posframe-mode
    ✓ (96/433) persp-mode.el: d0f8eb0 -> 67be9fe [8 commit(s)]
        67be9fe Up version.
        43f49cd persp-tramp-save-buffer -- save port information.
        cc5d552 Up version.
        fc129b7 Make persp-delete-other-windows more safe.
        7bca3b4 Fix persp-tramp-save-buffer.
        8f192c3 Up version.
        190358e %s -> %S in error message format.
        3e66d13 When loading from file in case of errors try to load as much as possible
    ✓ (99/433) evil: fdf8a72 -> 26168f1 [48 commit(s)]
        26168f1 Update ] and [ markers when doing operator
        2e30d83 Update docs
        88da852 evil transient mouse selection (#1706)
        a13a05f Add evil-execute-last-recorded-macro à la nvim
        d43fe06 Add [S-left] and [S-right] bindings for insert state
        51bd3c3 Remove z kb macros for discoverability
        b27997b  Remove make-variable-buffer-local from variables (fixes #1416)
        a42516d Fix compiler warnings
        cddc4a6 Shorten doc-strings
        298273f Suppress operator for evil-set-marker
        a3110e6 Revert "Suppress operator for some normal state commands" partially
        840084f Fix evil-select-paren #1673 for regexp special chars (#1696)
        7b4a9b4 Fixup evil-select-paren for multichars delimiters
        f631618 Add tests for c-w yanking word in evil search
        3b73f82 evil-ex-completion-map/evil-ex-search-keymap respect evil-want-C-w-delete
        a760514 C-w support yank word when search-module is 'evil-search
        b46acf2 Fix evil-ex-substitute up to EOB
        30980b3 Fix up the cmds that scroll relative to cursor
        c503bcc Add test
        782323a Handle gj/gk when tracking EOL
        [...]
    ✓ (107/433) evil-nerd-commenter: b1a9222 -> 9609fb1 [1 commit(s)]
        9609fb1 fixed: last char is missing^Cn multiline commment object
    ✓ (116/433) evil-collection: c1ede88 -> c3611ae [6 commit(s)]
        c3611ae shortdoc: (S-)?tab to navigate buttons
        d1dec4e eglot: add bindings for xref-find-definitions-other-(window|frame)
        f45f4ab Add bindings for crdt.el's menu modes
        6306aa7 pdf: Add binds for `pdf-history-forward/backward`
        76d003c emms: Use line-beginning-position
        665d5c9 mu4e: remove the inaccurate description
    > In repository "ts-fold", remote "origin" has URL
      "https://github.com/jcs090218/ts-fold.git"
    but recipe specifies a URL of
      "https://github.com/emacs-tree-sitter/ts-fold.git"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

      How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4)       Really delete remote "origin"? (y or n)     ✓ (120/433) ts-fold: 17d131f -> c3da552 [9 commit(s)]
        c3da552 tests(test.yml): Add test for Emacs 28.2
        0174027 Fix typo/grammar in error message (#34)
        1cb7841 Add FUNDING.yml
        bbb1eae docs(CHANGELOG): fix PR number for #33
        9f24d29 Julia language parser. (#33)
        28409a0 docs: Update repo link (#32)
        3b2e70d tests(test.yml): Add workflow_dispatch
        f0804a2 docs(CHANGELOG): update (#28)
        443ba51 feat(ruby): Enhance Ruby parser (#26)
    ✓ (121/433) emacs-format-all-the-code: 7e375c0 -> c237c4c [6 commit(s)]
        c237c4c Add `ocamlformat` as an OCaml formatter
        d01a070 Add autoload for format-all-ensure-formatter
        4d7a70a Add `Verible` as a Verilog formatter (#209)
        8f40631 Improve format-all-default-formatters customization
        48f79e8 Provide a customizable lighter for format-all-mode
        f5e97b4 Support fourmolu version 0.8
    ✓ (126/433) auto-yasnippet: db9e0dd -> f54fb42 [8 commit(s)]
        f54fb42 Fix badge branch
        83f6e5a Add workflow CI / Test badge
        62a3e84 Clean up workflow run
        39a3cdc Update auto-yasnippet-test.el
        8b3290d Create test workflow
        7ef65b8 Put back aya-create-one-line
        b63ddd7 Fixup package commentary
        85592ff 1.0.0
    ✓ (127/433) snippets: f957f8d -> 03a62fe [1 commit(s)]
        03a62fe snippet(csharp): add foreach
    ✓ (128/433) ctrlf: cefb0af -> e4bd61e [3 commit(s)]
        e4bd61e Integrate evil with ctrlf-style-alist. (#124)
        63d27a0 Do not run CI on Emacs master (#125)
        9b32106 README: document how to configure `ctrlf-minibuffer-mode-map` (#121)
    ✓ (129/433) diredfl: 62b559e -> 94bd99e [1 commit(s)]
        94bd99e Add Emacs 28.2 to CI, cut down size of matrix
    > In repository "dirvish", HEAD on default branch "main" has diverged from "origin/main"

         1) Abort
         2) Merge "origin/main" into "main"
         3) Rebase "main" onto "origin/main"
         4) Reset "main" to "origin/main"
         5) Magit log "main...origin/main" and open recursive edit

      How to proceed? (1, 2, 3, 4, 5)     ✓ (132/433) dirvish: 845cd61 -> ec41006 [1046 commit(s)]
        ec41006 refactor(side): use `no-other-window` window parameter
        3dc059b docs: resolve TODOs and improve wording
        f3febed perf(side): get rid of recursive `buffer-list-update-hook` call
        6c76aab feat(side): add `dirvish-side-follow-mode`
        4813c66 fix(core): do not reuse sessions from other tabs (#156)
        4bab220 fix(core): dirvish-tramp-preview-dp -> dirvish-tramp-dp
        0beee69 fix: record history entries by default
        99d06c0 docs: add 2 faq entries
        a33dbb5 refactor(core): add `dirvish-preview-environment` user option
        ac00775 refactor: improve preview update
        4a99dc5 refactor(yank): add back persistent task logging (#150)
        86a9ff5 perf: record subtree depth at insertion
        b858719 refactor(yank): tweak `dirvish-rsync`'s dest reader, closes #155
        501f6c3 refactor: preview small images as it is
        11a3bec refactor(extras): improve setter of `dirvish-ui-setup-items`
        4f2642c feat(core): recognize `cr2` and `arw` extension (canon/sony DSLR)
        8333b72 fix(yank): void-function error in subprocess, closes #153
        4f636bf fix: `tramp-get-connection-property` takes 3 args in Emacs 28 (#154)
        252764f docs: add instructions for Emacs newcomers
        a877ba8 refactor: improve gnuls checking / preview on remote hosts
        [...]
    ✓ (135/433) ibuffer-vc: 5fa6aea -> 813d2de [1 commit(s)]
        3e966a9 Add support for the SCCS backend
    ✓ (136/433) info-colors: 47ee73c -> 2e237c3 [1 commit(s)]
        f110240 Don't quote keys in cl-case
    ✓ (138/433) browse-at-remote: cef26f2 -> 010639f [103 commit(s)]
        2dcdcf1 add gitlab.gnome.org
        6030f01 Fix stash URL for detached head.
        e4dd9c4 Fix incorrect indentation in README
        a61bda1 Bump version to 0.13.0
        dec6bf0 Include sourcehut in comments and documentation
        166c110 Add support for sourcehut (git.sr.ht)
        9f4a532 Reliably extract SHA1 from magit-revision buffers
        82c741c Add phabr to readme
        2ffeb5d Bump version update readme
        08e1b92 Documentation update and version bump
        163f587 Add support for Phabricator URLs
        3342bc2 Add Gist (gist.github.com) support
        e34aceb Support VC's log-view-mode
        6141806 Strip port from URL unless protocol is HTTP/HTTPS
        898aea3 Fix typo
        47bab99 Minor merge issues, bump version, updates in readme
        cd2ccda Add support for repositories that are hosted on gnu cgit
        b144d98 "stash" is also a valid value in browse-at-remote-remote-type-domains
        f7c115e Suggest configuring browse-at-remote-remote-type-domains for unknown domains
        10bbe72 Use Emacs' built-in URL parsing
        [...]
    ✓ (139/433) magit: 8a0cc83 -> 87e68e0 [52 commit(s)]
        87e68e0a magit-tag-release: Fix case when no default is detected
        8158b484 magit-list-module-paths: Ensure they are relative to top-level
        ccd82ffe magit-reflog-labels: Add entry for "rewritten"
        74d14c2d magit-log-reflog-re: Handle "rewritten during rebase"
        2fee806a magit-rebase: Add --update-refs
        0ef98ef5 test: Comment failing magit-toplevel:tramp
        b52922a3 magit-get-submodule-name: Adapt to change in Git v2.38.0
        619b6a14 make: Suppress warning about obsolete autoload package
        5d6c01e2 magit-commit-squash-internal: Restore window conf after showing diff
        47df80a4 magit-stash-push: Don't unquote inside group vector
        1c51352e magit-branch-delete: Improve suggested branch for checkout
        557ab2c0 magit-diff-wash-diff: Fix headers for "git log -L --no-prefix"
        37c0c857 magit-diff-wash-diff: Cosmetics
        304b1730 diff: Remove partially broken and unnecessary kludge
        ce0746ab diff: Mention when a file is a binary
        3e833f36 AUTHORS.md: Update list of contributors
        71717126 manual: Mention with-editor-filter-visit-hook in performance hint
        9a69e3d4 magit-blame--make-margin-overlays: Fix beginning of each overlay
        d24c5107 Remove duplicated `and'
        169dbf9c manual: Fix a typo
        [...]
    > In repository "git-timemachine", remote "origin" has URL
      "https://codeberg.org/pidu/git-timemachine"
    but recipe specifies a URL of
      "https://github.com/emacsmirror/git-timemachine.git"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

      How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4)       Really delete remote "origin"? (y or n)     ✓ (140/433) git-timemachine: ca09684 -> 77a3e72 [1 commit(s)]
        af88b1d remove unnecessary git-timemachine-completing-read-fn
    ✓ (141/433) git-modes: eca3bb4 -> 4f9ad30 [1 commit(s)]
        4f9ad30 make: Suppress warning about obsolete autoload package
    ✓ (147/433) eshell-syntax-highlighting: 8e3a685 -> 1ba39a9 [1 commit(s)]
        1ba39a9 Do highlighting silently to avoid changing undo data (#10)
    ✓ (150/433) emacs-libvterm: 3155a47 -> 19c84e9 [20 commit(s)]
        19c84e9 Reflect human-friendly prompt change in README to configuration file
        c1c1071 Use `prompt_pwd` to format `/home/myuser/mydir` as `~/mydir`
        e9bfe56 fix #632 Meta/Alt not working in terminal/non-graphical mode
        b32f620 Fix type for vterm-clear-scrollbark-when-clearing
        0838ee3 check  libvterm version,make it compile with libvterm<0.2
        54bef7c update readme about libvterm 0.2 is needed.
        e19dc2b make-obsolete for all vterm-send-C-[a-z] vterm-send-M-[a-z] etc.
        7feb9c3 reimplement OSC 52 with VTermSelectionCallbacks from libvterm v0.2
        679b43f use mirror https://github.com/Sbozzolo/libvterm-mirror.git v0.2
        0091bb0 fix document of vterm-enable-manipulate-selection-data-by-osc52
        4e9b3f3 fix compile warning on emacs 29
        dac3187 unbind M-{A-Z} #575 related
        f65916b fix #622
        4b5539c Better vterm-undo key bind and close #613
        aff8bad delete recent added vterm-send-meta-{up/down/left/right}
        9ac4aeb prefer vterm--self-insert
        1ed2646 rewrite vterm--self-insert/vterm-send/vterm-send-next-key.
        6f49cae try fix #598. `ESC =`(Application Keypad (DECKPAM)) as control seq.
        c66c324 Add vterm-send-meta<up,down,left,right> functions and keybindings
        ceddd7a Declare variable before first use
    ✓ (151/433) flycheck: 8541a61 -> d72c29f [5 commit(s)]
        81b05c55 Remove `-`, not `/dev/stin`, from hadolint output
        c64f3331 Fix typo adds 't' to 'no'
        f15bf5a8 put global-flycheck-mode in 'flycheck group instead of 'flycheck-faces
        4d5380cb update flake8 config file list
        6f054dbd Set run_name to __main__ when running python modules
    > In repository "spell-fu", remote "origin" has URL
      "https://github.com/emacsmirror/spell-fu.git"
    but recipe specifies a URL of
      "https://codeberg.org/ideasman42/emacs-spell-fu"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

      How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4)       Really delete remote "origin"? (y or n)     ✓ (154/433) spell-fu: bfd017f -> d907800 [6 commit(s)]
        d907800 Cleanup: replace 'if' with 'cond'
        ba5942c Fix #31: Failure to detect updated symlinked dictionaries
        3e532cc Cleanup: sharp-quote function
        33a71c8 When using jit-lock-stealth, ensure words out of the view are checked
        ad26435 Fix #13: Every word marked as incorrect on MS-Windows
        2288af9 Add support for buffer local word-lists
    ✓ (157/433) citar: 146f2cb -> c37a482 [14 commit(s)]
        c37a482 Call predicate on candidate display string (fix #708)
        4a302fc citar-file: Unescape filenames in citar-file--parser-default
        24a800b Fix linter warnings on indentation and long docstring lines. (#698)
        cf36790 More formatting
        b0605c3 Fix indent formatting
        52050ca Update docstrings, KEY arg to CITEKEY
        219a69c Clarify docstring on citar-open-note
        60cc30e Add at-point function for org property drawers
        f66177b Add multiple files example to README
        b0fefab Add binding hint to multi UI
        731c0ae Remove bold from default highlight face
        beb9ce9 Remove obsolete variables
        9d7088c v1.0!
        8f81ccb Bump parsebib version
    ✓ (158/433) citar-embark was updated indirectly (with citar)
    ✓ (160/433) parsebib: 175a1bd -> 1efca92 [6 commit(s)]
        1efca92 Wrap `not` with `any` in rx for older emacs (#27)
        f87b0fd Update version number.
        819f6f2 Remove unused functions.
        db69b09 Update README.md on `parsebib-TeX-markup-replacement-alist`.
        eabfb0d Update doc strings for TeX-replacement functions and variables.
        f41befa Speed up markup removal (#25)
    ✓ (161/433) citeproc-el: 406bd99 -> e705911 [6 commit(s)]
        a20411a Parse formatting in locators
        adc8e09 citeproc-rt.el: Support underline formatting in CSL text fields
        d89df23 Don't test on Emacs 26
        6f4d515 Use short title for title-only cite
        0beab2c Use short title for title-only cites
        2c9df46 Use the biblatex->csl converter to convert org-bibtex entries
    ✓ (165/433) realgud: 45f7e44 -> aff03ae [1 commit(s)]
        a670add Use the right variable for trepan3k minibuffer history.
    ✓ (167/433) dap-mode: e2a37cc -> 2879578 [10 commit(s)]
        2879578 Drop with-lsp-workspace calls because debug-session-workspace is not used
        442aef5 Make sure dap-ui buffer is created
        0f76925 Declare posframe-mouse-banish
        6b2cca8 Better dap-ui-locals
        5d5043f Utilize dap-ui-default-fetch-count
        7f924d7 Add support for VSCode Tasks (#578)
        b5a617f `cpptools+codelldb`: Updates, Better detection of the architecture (#664)
        61c8825 Refactor debug provider names (#662)
        5821215 Fix #314. Give other tooltip-functions a chance to run. (#663)
        192c4e1 Debug template for current file and root cwd (#660)
    ✓ (168/433) posframe: 0d23bc5 -> 3084cb6 [2 commit(s)]
        c6026ba only redraw when reusing the existing posframe
        0c5e57a v1.1.8
    ✓ (169/433) envrc: 7f36664 -> 0cd450a [10 commit(s)]
        0cd450a Remove defunct note from README
        08cffdc Clarify README wording
        433df84 Fix other quoting issues
        437cc27 Unquote `envrc-direnv-executable` to have executable in process call
        fb68fd2 Use `envrc-direnv-executable` custom variable in tests
        ef192d2 In test harness, handle when envrc-debug is unset
        8a73947 Add defcustom for envrc-direnv-executable
        9b772ce envrc-file-extra-keywords: Restore use_{guix,flake,nix}
        c4d430e Add Emacs 28.2 to CI
        936e45e add new stdlib keywords
    ✓ (170/433) docker.el: 8d0429d -> cc0046e [3 commit(s)]
        cc0046e Remove docker-tramp dependency
        3173403 Remove MELPA stable tests because transient don't support it
        670b7c3 Provide default list of Docker Compose projects
    ✓ (172/433) dockerfile-mode: c7e4e25 -> 52c6c00 [5 commit(s)]
        52c6c00 Update docstring
        e2d59c7 Fix various lint warnings
        099bc8d Remove unnecessary configuration
        5e7096d Recognize Containerfile
        73a8bcc Fix: remove repeated switch in docstring
    ✓ (173/433) editorconfig-emacs: 1f6f16c -> bd1d9c3 [5 commit(s)]
        bd1d9c3 Check `filename` rather than `buffer-file-name` for consistency (#280)
        bcd3775 Prepare v0.9.0 (#275)
        f529bbe Fix package load for use-package usage (#277)
        44bcfcf  Add fixes for Emacs 29 (#276)
        541298a tests(build.yml): Use latest minor version number (#274)
    ✓ (174/433) quickrun: 314beae -> 548b64c [578 commit(s)]
        548b64c Use -A for deno
        04ab23b Add truncate lines option
        621dfb1 Avoid pop-to-buffer on multiple runs
        4da5bc5 docs(README.md): codeblock supported backend
        d0bd252 Add support MASM
        a33b096 docs(README.md): Add support asm
        abbd70b rev indentation
        0b1ae06 fix compile
        48efb3f Update quickrun.el
        d4cc5e9 docs(README.md): remove travis badge
        449c608 fix compile warnings
        0994d46 add changelog
        b8a9b71 Add support for Deno
        fb7bf53 support select compile-only flag
        c32926e rename changelog
        e770215 add license file
        9af221d fix eask file
        0b01c16 Add quickrun-select command
        1a334ed modernize package
        62c5e2a fix indentation
        [...]
    ✓ (179/433) emacs-request: 38ed1d2 -> 2c33e45 [511 commit(s)]
        78e81ed Fix docstring has wrong usage of unescaped single quotes
        7444e76 package is now single-file
        62e9f2b 28.2
        4dad570 Closes #213
        bb277bc Fix emacs native compilation warning
        8ca33f7 fixes issue with missing mime-types
        3336eaa Semeai condition
        68003b3 Fixes #205
        c96a45d emacs26-3 and werkzeug flaps under global-auto-revert-mode
        2b68b3c Oh I didn't need to do that
        99ae82f Fixes #202
        f3a5b43 Cask rapprochement
        f795d03 shell env variables are in a separate subspace
        c076219 okay, now cask24 is failing too
        572a900 I may need to eval calls
        c92102f On 20210213, emacs24 couldn't download packages from elpa
        ef231e1 request-response-headers
        8e6aaa5 Revert "add headers slot into request-response structure"
        ec35961 In for a penny, in for a pound
        576585d reuse GITHUB_HEAD_REF
        [...]
    ✓ (182/433) lsp-mode: ece9bcd -> dfda673 [70 commit(s)]
        dfda673 Revert "Dispatch each lsp--parser-on-message in next message loop (#3087)" (#3791)
        31645f9 :rocket: `feat` Add Nix lsp, nil (#3789)
        2e2d5dc Suggestion of adding `clients' to `load-path' (#3788)
        9a3708c don't put evaporate to lens overlays (#3772)
        48cf201 Fire up lsp when lsp-mode is called
        ac6e3b8 Remove double resolving
        af4bd15 Remove deprecated `--background-services-enabled` flag to FSAC (#3776)
        2fdfb51 Improve project root print on conected message (#3775)
        a3b3c15 patch for snippets in ts-ls (#3766)
        a2ca5ae Update lsp-mode.el (#3768)
        4f5754f Add more settings for lsp-nim
        287cdcb Jump to current workspace in lsp-describe-session if applicable (#3758)
        6122ec5 docs: Fix stray comment in lsp--apply-text-edit (#3756)
        c44eac7 Upgrade lsp-xml version and add new formatting options (#3764)
        89b0e87 *lsp-help*: allow to open link with markdown-follow-link-at-point (#3759)
        759fb79 lsp-rust: add semantic token modifiers (#3668)
        c9db552 lsp-ansible: update settings
        facd782 hide parent details in imenu nodes (#3752)
        178be6f fix header for forgetting workspace folders (#3751)
        bbce14c lsp-eslint: support glob patterns for workingDirectories parameter (#3747)
        [...]
    ✓ (183/433) lsp-ui: 8d4fa5a -> 3cd7cc6 [3 commit(s)]
        3cd7cc6 use lsp-feature? to check for hover capability instead of lsp--capability (#734)
        d8cce7d new command lsp-ui-doc-toggle
        e5a5623 Allow lsp UI doc hide from focused frame (#729)
    ✓ (184/433) consult-lsp: 19606a0 -> 58b5414 [2 commit(s)]
        58b5414 Bump dev version
        c2ec2c5 fix(file-symbols): use end-line, stop assuming ht
    ✓ (185/433) magit was updated indirectly (with magit)
    ✓ (186/433) forge: ed8abda -> 45b06b8 [9 commit(s)]
        45b06b8 Remove support for obsolete libsqlite3 and broken sqlite3 backends
        3336452 forge--branch-pullreq: Cosmetics
        ce212f8 make: Suppress warning about obsolete autoload package
        2a2c6dd Make forge--buffer-draft-p public
        6de2094 forge--db-dump: Copy binary db if sqlite3 cannot be found
        6a820a4 forge-create-pullreq-hook: New hook
        9556d3b make: Print message for texi target
        bb2041f manual: Regenerate texi
        351a780 manual: Use @insertcopying
    ✓ (189/433) magit-todos: 67fd80c -> c5030cc [4 commit(s)]
        c5030cc Change: Require Emacs 26.1 or later
        c6d9e64 Tidy: Compilation warnings
        45bd4ae Meta: Update makem.sh
        f7ce396 Change: Load org only when needed
    ✓ (190/433) makefile-executor.el: d0a34c3 -> 170d14d [13 commit(s)]
        3e7ad8b fix: unbalanced parenthesis
        2009402 Use grep -E instead of egrep
        50a0166 Avoid this triply-repeated conditional check.
        ac2e5a3 Avoid nil.
        440de68 Rework header comment.
        51f8474 Better version number.
        645cf09 Remove projectile mentions from docs.
        0b25999 Fix argument invocation errors.
        2b446fe Fix date.
        0f786e4 Excise last (featurep 'project) check.
        12736ed Bump version.
        a291bc8 Remove projectile.
        72e42ec Define makefile-executor-project-root.
    ✓ (192/433) password-store: c4d8a1d -> dddca73 [2 commit(s)]
        dddca73 tests: Replace short OpenPGP keyids with fingerprints
        47f8d95 emacs: Add command password-store-generate-no-symbols
    ✓ (194/433) pdf-tools: bb0b71f -> d6980bc [13 commit(s)]
        d6980bc Enable testing against MacOS in CI/CD!
        5350677 Add make targets to start / stop the podman VM
        e6d1df4 Speed up server testing by keeping the containers around
        a4905d8 Revert "Adds translattion of highlight annotations"
        aec8ecd Add non-transparent text selection to known problems
        2ce06dd Address some byte-compiler warnings
        a316013 Fix nix-shell pkg-config dependency name
        49078c7 Fix: misuse of cl-ecase
        45b0570 Fix: Warnings and <26.1 code
        1a0a30c Revert "synctex_parser: fix vasprintf() not exists in non-GNU environment (#134)"
        bea5ddb synctex_parser: fix vasprintf() not exists in non-GNU environment (#134)
        c3d227c Don't depend on gcc when building with `nix-shell` (#135)
        6df4160 Fix: remove execute permisions from temp files
    ✓ (198/433) kurecolor: 2016973 -> 0e3b9df [96 commit(s)]
        0e3b9df Fix push pages
        3dabc10 Move tests to /dev
        ba6f0f2 add mirroring
        190756d examples updated to use aliases: group & examples
        7f81c9c Update README.md
        e7e27e4 Update README.md
        8af9001 ~> approx equal for floats and lists of floats.
        abd5047 Approximation expects correct rounding.
        052e0a2 Fix broken test case...
        48b2ecb Clean up
        ac8a97b Use cond instead of pcase T_T
        e54d3c1 Add approximate equality (scalar floats working.)
        d86d169 Ok... fix the test name...
        da59a6f Get example 1:1 test working first...
        22169e2 Ignore any DS_Store file...
        c4b4670 Ignore Macos DS_Store files
        58700b9 Update etd. Each example will be a test.
        ec27710 Update README.md
        553e852 Fix bad formatting
        e3331e7 1.6.1
        [...]
    ✓ (200/433) tree-sitter-langs: deb2d86 -> 00738cb [12 commit(s)]
        00738cb Release 0.12.4
        32c0306 Bump go grammar
        11d1b78 chore(queries): Highlight enum as keyword
        6d18db5 Release 0.12.3
        d663cbc Add perl grammar
        8ca4fdd Changelog update.
        df272b6 Add Haskell mode and highlights.scm
        4896a56 Release 0.12.2
        b5a27cf Add yaml grammar
        5c6900a Release 0.12.1
        68e637e Bump java grammar
        c283571 Add verilog to list of languages
    ✓ (201/433) evil-textobj-tree-sitter: 7ec5835 -> 087c3c3 [9 commit(s)]
        087c3c3 Update tree-sitter queries to latest
        b986367 Update tree-sitter queries to latest
        490b266 fallback to builtin queries if no major mode in user queries
        3c9a444 Update tree-sitter queries to latest
        fad2178 Update tree-sitter queries to latest
        c2408aa Update tree-sitter queries to latest
        4510e31 Update tree-sitter queries to latest
        f0b887f Update tree-sitter queries to latest
        0df263f Update tree-sitter queries to latest
    ✓ (202/433) osx-trash: af74a20 -> 90f0c99 [1 commit(s)]
        90f0c99 Add new osx-trash-command to deal with incompatible implementation
    ✓ (206/433) paredit: d0b1a2f -> e4a67f4 [3 commit(s)]
        e4a67f4 Add .gitignore file.
        81e069b Credit Javier Olaechea and Vladimir Sedach.
        42500e5 Note that Paredit Mode and Electric Indent Mode are incompatible.
    ✓ (209/433) clojure-mode: ad322e9 -> 414157c [11 commit(s)]
        414157c Fix whitespace
        d472982 Fix function definition names being not highlighted
        49c1615 Tweak a changelog entry
        24ee368 Make function definition regexp only look for 'clojure.core/defn' forms
        4a5f011 Replace obsoleted function
        0b03238 Fix byte-compile warnings quotes in docstring
        68e0e13 [Fix #377] Fix font locking for def forms (#630)
        0af29f4 Tweak some markup
        52f3e1f Tweak some changelog entries
        905abd0 Set add-log-current-defun-function (#629)
        0be365a [Fix #581] Fix font locking for keywords starting with a number (#628)
    ✓ (210/433) clj-refactor.el: 1bd7b09 -> 8300d5c [27 commit(s)]
        8300d5c 3.6.0
        e53606b Add Changelog entry introducing #532
        0c8d818 Disable the reader-conditional term of `cljr--language-context-at-point`.
        a3c0cb4 Prefer explicit parsing instead of destructuring binding per reviewer
        c28773d Document feature paths inside `cljr-slash`
        16da22c Improve documentation for `cljr--call-middleware-suggest-libspec` and `cljr--language-context-at-point`
        a1c1988 Assert that completing-read is called or not called for each example
        52fe70a Documentation changes suggested in code review
        e27d860 Shadow cljr-slash-uses-suggest-libspec to enable feature without using setq in tests
        72685e4 Expand test coverage for `cljr--language-context-at-point`
        843caf2 Add `cljr-slash-uses-suggest-libspec` flag to prefer new middleware
        44106f3 Add `cljr--language-context-at-point` for detecting context
        343698a Introduce `cljr--call-middleware-suggest-libspec`
        bcb4627 Fix failing tests by expecting value instead of macro expansion
        cd97626 Use refactor-nrepl 3.5.5
        8f511ea Update circle-ci environment to include value for TERM
        35cca56 Fix regex for removing prefix from ns alias
        7011b06 Remove prefixes including digits and various orderings
        10633c1 Change `cljr-ns-alias-at-point` to detect symbols at point before /
        ead4813 Extract cljr--alias-here helper and add pending test cases with issue
        [...]
    ✓ (211/433) cider: 9577dbb -> e9324ac [22 commit(s)]
        e9324acf Consecutive result overlays can now be seen (#3259)
        d08609fe Add support for Clojure Spec 2
        33c26b2a Bump the injected cider-nrepl
        aa9cb3f3 Bump the dev version
        92c1b6de Tweak a changelog entry
        055545df Add a changelog entry
        e75706f5 [Fix #2561] Disable undo in *cider-test-report* buffers
        b8d8de60 Disable undo in cider-stacktrace buffer
        101671c0 Bump the inject cider-nrepl version
        20debc82 Fix several typos
        14eb0229 Remove needless quote from the choices
        5bba4856 Bump the injected nREPL version to 1.0
        7d1a989d Switch back the docs version
        700ded1d Release CIDER 1.5 ("Strasbourg")
        73fe0916 Tweak the changelog
        90561f1c Add evaluate and tap commands for last-sexp and sexp-at-point (#3240)
        f54101f5 Prefer dashes over stars for bullet points
        de51a0b1 Tweak a changelog entry
        10cc3905 Tweak some changelog entries
        68974c9f Tweak an obsoletion message
        [...]
    ✓ (218/433) elisp-demos: 4b51dff -> 792be70 [1 commit(s)]
        6e74eff elisp-demos.org: Add backquote to json-encode
    ✓ (219/433) flycheck-package: 615c1ed -> 3a6aaed [1 commit(s)]
        3a6aaed Add Emacs 28.2 to CI, cut down size of matrix
    ✓ (221/433) emacs-buttercup: 62176a3 -> eaa4b3c [333 commit(s)]
        eaa4b3c Bump version: 1.27 → 1.28
        ae884f1 Accept un-evaluated functions in buttercup--enclosed-expr
        001adc0 Bump version: 1.26 → 1.27
        10d5d88 Test on GNU Emacs 28.2
        bff022e Use the name instead of the symbol in *-define-matcher-for-*-function
        e2b77ac Check position of the :var and :var* keywords
        9022546 Bump version: 1.25 → 1.26
        91b541a Add .elpaignore
        e083d67 Makefile: Rename test* targets check*
        9f3d181 Makefile: Remove release target and associated variables
        cdbb8b0 tests: Add tests for buttercup--enclosed-expr
        0e26b1b Clean up buttercup--enclosed-expr
        4cbd106 tests: Use buttercup--wrap-expr instead of make-list-of-closures
        435fc0d tests: Fix some buttercup-expect tests
        ec4d94f tests: Create enclosed expressions with buttercup--wrap-expr
        8dda6ef Refactor the expect macro
        ef293a6 Fix: (buttercup--enclosed-expr) byte-code functions
        ceedad5 Test on GNU Emacs 28.1
        ba62f80 Bump version: 1.24 → 1.25
        42a1d7e tests: Add a simple load test
        [...]
    ✓ (225/433) typescript.el: d1123e0 -> d79551c [1 commit(s)]
        b99d893 fix(fontlock): fix special forms/ternary mistaken for method declarations
    ✓ (238/433) lua-mode: d17a00c -> 3e783c9 [1 commit(s)]
        348e69b Enable lexical-binding for tests as required by buttercup
    ✓ (239/433) markdown-mode: 0b8dc23 -> 7030c72 [5 commit(s)]
        f5a9ef6 Update test configuration
        cce3249 Fix issue URL
        9bac1ca Fix italic fontification after bold markups
        883c846 Update testing emacs versions
        518191b Fix deprecated warnings on Emacs 29.1
    ✓ (242/433) grip-mode: 6d6ddbe -> e1e8ee9 [4 commit(s)]
        e1e8ee9 New option: grip-sleep-time.
        2bb9f66 Update markdown toc.
        a607f3e Update toc of README.
        acb97fc Update to 28.2 in CI.
    ✓ (244/433) nix-mode: b3f71c7 -> b76c847 [9 commit(s)]
        b76c847 Don’t set search string when it’s empty
        c229d66 Remove nix-search require
        5efb538 Fix auto-mode-alist for drvs
        1f93977 Bind l to nix-store-show-log
        e0c057f Add function to get nix store log path
        26928b8 Add `nix-store-show-log` to open a log file from nix-store-path mode.
        098433b chore(deps): bump cachix/install-nix-action from 17 to 18
        e1f3af5 Make flycheck happier
        c8f33e5 Differentiate realised/unrealised store paths
    ✓ (245/433) nix-update-el: 1dd1434 -> aab70a3 [1 commit(s)]
        aab70a3 Allow C-u to force refresh the rev field
    ✓ (246/433) org: 4db67da -> 48b237d [20950 commit(s)]
        48b237d9e org-attach-attach: Fix storing link to attached files
        d4e3598ab fixup! org-babel-read: Fix cells like '"string" more'
        633ca9e69 org-babel-read: Fix cells like '"string" more'
        9a3dd429b org-babel-import-elisp-from-file: Fix when \"s are not around
        f8a9cd230 org-babel-eval: Return command output even upon failure
        ab7eff9d9 org-babel-eval-error-notify: Avoid uninformative empty error buffer
        1ef420b19 org-babel-comint-with-output: Handle output without trailing newlines
        69e3a4db3 org-babel: Refactor temporary directory usage
        2f5e7103e ox-odt: Improve link generation in 4e5c737311
        524e0e0b7 test-ob: Test indentation of multiline text in list output
        a83edd624 fixup! ob-shell: Fix multi-line scripts in sessions
        801c93638 ob-shell: Fix multi-line scripts in sessions
        bed47b437 test-ob-java: Test Java source block header arguments at all levels
        e70057879 ob-core.el: Fix indentation of multiline text in list output
        85ab64c2b org-clock-select-task: Do not offer non-printable characters in selection
        3502ce2db ox-odt: Fix newlines replaced by spaces in Han script
        cce846e5f org-manual: Clarify `org-timer-start' command description
        d98a49648 org-lint: Fix regexp when matching header-args
        ee3dbb0fd ob-java: Define the list of all supported header arguments
        deb1517fe org-macs.el: Do not compare wall time and file modification time
        [...]
    > In repository "org-contrib", HEAD on default branch "master" has diverged from "origin/master"

         1) Abort
         2) Merge "origin/master" into "master"
         3) Rebase "master" onto "origin/master"
         4) Reset "master" to "origin/master"
         5) Magit log "master...origin/master" and open recursive edit

      How to proceed? (1, 2, 3, 4, 5)     ✓ (247/433) org-contrib: 39e2abc -> aa104c0 [2429 commit(s)]
        aa104c0 [PATCH] Remove libraries that are in transition to be part of Org
        65711dc [PATCH] Remove libraries that are in transition to other repositories
        6422b26 fix(org-checklist.el): change org-make-checklist-export (Emacs 28+ cl)
        7f32f80 file-name-directory return nil with arg file
        caf613d org-depend: Fix obsoletion warnings
        dba0972 lisp/org-eldoc.el: Fix propertizing of non-string header args
        c6aef31 lisp/org-contrib.el: Bump version to 0.4
        89ddcab *el: Fix Homepage keyword
        56fdeef README*: Update the list of files to delete from the next release
        3dd9841 Delete files
        15b03d5 * lisp/org-contacts.el: Update homepage
        e6cb6ca Replace removed `remove-if' by `cl-remove-if'
        4936783 lisp/org-eldoc.el: Fix inf-loop when point in org src blocks
        f237d67 lisp/org-eldoc.el: Whitespace change
        a33dd6f Rename some obsolete functions to their newer names
        5766ff1 Don’t assume Emacs internal timestamp format
        9dc8f49 Don’t assume Emacs internal timestamp format
        65821e4 Support numeric argument values in src definition lines
        e14dfea README*: Add org-contacts.el to the list of file to remove
        1ae5f90 org-contacts.el: Add the new homepage
        [...]
    ✓ (248/433) avy: ba5f035 -> 955c8de [3 commit(s)]
        955c8de avy.el (avy--overlay): Avoid error on empty string
        6f9eefa avy.el (avy-process): Assume avy-action-oneshot will be let-bound
        fd7b02f Add `avy-action-oneshot` variable to redefine avy-action locally
    ✓ (256/433) orgit: b33b916 -> 5036c3d [1 commit(s)]
        5036c3d make: Suppress warning about obsolete autoload package
    ✓ (257/433) orgit-forge: 8baf1de -> 3a54569 [1 commit(s)]
        3a54569 make: Suppress warning about obsolete autoload package
    ✓ (258/433) org-download: 947ca22 -> 19e166f [3 commit(s)]
        19e166f Also make available for derived modes
        7ca67df org-download.el (org-download-image): Add org-journal-mode
        69c57bd fix: delete formatted link
    ✓ (259/433) gnuplot: 803033e -> f420219 [3 commit(s)]
        f420219 README update
        d50c352 Fix a few warnings
        d134129 Do not distribute gnuplot.info with gnuplot.el
    ✓ (264/433) org-tree-slide: 3faa042 -> d6529bc [1 commit(s)]
        d6529bc Update docstrings
    ✓ (265/433) org-re-reveal: 6f78a0a -> 941aa4b [8 commit(s)]
        941aa4b Version 3.16.1
        7344b07 Refactor test for presence of math plugin
        d89d2b1 Turn SPDX headers into keywords
        5ab524b Version 3.16.0
        e73e2bc Document MathJax alternatives
        e076a82 Add test case of math plugin
        8bf88cc Prefer math plugin over MathJax script element
        e227cbc Quote apostrophes properly
    ✓ (266/433) reveal.js: e219184 -> f6f657b [2307 commit(s)]
        f6f657b 4.4.0
        fb68f1c fix getAttribute exception in notes plugin #3285
        4681323 remove doppler
        c1c4145 fix merge error, closes #3277
        8a97ad5 prevent extra \n at end of single notes #3010
        b23d15c fix issue were auto-animate could interfere with inherited line-height
        a0e4860 fix issue with past/future vertical slides remaining visible in Safari 15.4 (closes #3164)
        62a85d5 Add generated files
        f9ce61e Support multiple aside notes elements per slide
        90bbe8b new shortcuts; alt+arrow key skips fragments, shift+arrow key jumps to last slide in the given direction #1105
        a3e8162 fix unmatched h3 in test
        bc5ca9a Fix unmatched h3-tags
        01d8d66 check for slides container too #2217
        e237fea better error message when '.reveal' root node is missing #2217
        9ca5068 Update whitespaces
        28509e0 fix test
        4d44382 Update build output for highlightjs
        20d7c87 fix(highlight): allow pre fragments
        ade2345 4.1.3 - accidentally published a local change to npm -_-
        a453ac0 4.1.2
        [...]
    ✓ (267/433) org-roam: 7f453f3 -> d95d256 [1 commit(s)]
        d95d256 (Docs): Fixed typos in the docs (#2256)
    ✓ (272/433) ob-restclient.el: 3ac834b -> 1b021ce [1 commit(s)]
        58b4ff6 Support variable assignment when expanding source blocks
    ✓ (276/433) php-mode: ca6ae67 -> c3c442a [25 commit(s)]
        b82b978 php-doc-annotation-tag inherits font-lock-doc-markup-face if defined
        9424e19 Update CHANGELOG
        fa8a969 Support prefixed tags in phpstan- and psalm-
        6abc996 Add PHPStan and Psalm type names to php-phpdoc-type-keywords
        29bbf49 Update Cask
        8366639 Add functions-txt subcommand to extract_functions.php
        51670f3 Add "=>" to php-mode token as pseudo-operator
        b3718d4 Copy thing-at-point-bounds-of-string-at-point function from thingatpt.el
        6049ad7 Add php-complete.el
        4609c93 Add php-leading-tokens
        5179a1c Copy c-end-of-token function from cc-engine.el
        6531053 Add php-defs.el
        651d524 Add script/extract_functions.php
        ff16da2 Update CHANGELOG
        c3f96b7 Add dump c-syntactic-context in test
        f926139 Fix indentation of expression continuation in arglist
        9aecbf0 Refactor :magic test
        e4c764a Fix quotes = and ' in docstring
        52f2f2d Fix Makefile
        85bacee Remove (c-lang-defconst c-opt-<>-sexp-key)
        [...]
    ✓ (280/433) phpactor.el: 34195f1 -> dde09ad [11 commit(s)]
        dde09ad Make phpactor-history-size custom variable and default desabled
        c652439 Add require php-mode and defvar php-mode syntax table in compile time
        09a35a3 Add fboundp check json-parse-buffer in compile time
        03eff6c Suppress unused varible
        da1a4c2 Fix doc string parameters
        209337f Update Phpactor
        1f4c339 Add :destination argument to phpactor-navigate command
        7fd9e47 Show relative path on phpactor-list-references instead of truncate
        1c55936 Add declare-function smart-jump-register
        9159485 Make company-phpactor.el lazy load 'company
        743cc9c Phpactor 2022.09.11
    ✓ (282/433) emacs-async: 6d164db -> ffde304 [283 commit(s)]
        0efee62 Add reference to Emacs bug/58446 in comment
        de04325 Change dired-async-skip-fast default to nil
        c6f3043 Fix error with file-attributes on remote files
        53addd0 Bump to version 1.9.7
        dbac401 Fix docstring and long lines
        d65fb9d dired-async-skip-fast is not used fix it
        ad2b253 Cosmetic cleanup of merged smart-async feature
        370ead4 Bump to 1.9.6
        53799e7 Skip async for fast operations
        9a8cd0c Delete async-pkg.el
        334c58e Add a .dir-locals file
        ea37e23 Untabify
        7c2da98 Update package-requires to fit with elpa
        43f4944 Declare package functions
        94850fd Reinstall async-pkg.el after elpa merge
        a153f5d Update headers and version number
        943a75c Fix paren error in dired-async
        d7e7f79 Update README
        0fd5d54 Make the async byte compile variable injection regexp "shy"
        00c6f3f fix inclusion of bytecomp variables
        [...]
    ✓ (286/433) lsp-pyright: c745228 -> 2fa2c89 [2 commit(s)]
        2fa2c89 Update README.
        fad6300 Update to 28.2 in CI.
    ✓ (287/433) anaconda-mode: 160e4e7 -> ca8edba [1 commit(s)]
        ca8edba Remove distutils dependency
    ✓ (291/433) emacs-python-pytest: 9bf8db3 -> 33c921a [7 commit(s)]
        33c921a Add --collect-only option (#65)
        66e9aaa git main these days
        98b5032 post-release changelog changes
        aef8b42 bump version for 3.3.0 release
        94fbb49 semi-random whitespace changes in readme
        da5df10 update changelog
        bec1483 Make "-v" argument-regexp match complete string (#64)
    ✓ (292/433) pyimport: a6f63cf -> c006a5f [1 commit(s)]
        5e537f8 Add support for pyflakes 2.5.0 output
    ✓ (294/433) restclient.el: ae79e7d -> 1fb5706 [1 commit(s)]
        1fb5706 fix: lexical-let is void when using cl-lib
    ✓ (296/433) restclient-jq was updated indirectly (with restclient.el)
    ✓ (297/433) rustic: baef1fa -> 4879922 [39 commit(s)]
        50cfa28 Fix some docstring issues that caused compiler warnings
        c996b6f rustic-save-some-buffers-advice: respect the `pred' argument of `save-some-buffers'
        0eca6e6 introduce command for nextest
        6ed570a also run tests for emacs28
        4c89ea7 fix last commit
        d8a93f7 append to rustic-compile-rustflags instead of replacing value
        ae86664 update rustic-save-some-buffers
        f48269c consider buffer-save-without-query in rustic-save-some-buffers
        66988ec add bound check to `rustic-cargo-auto-add-missing-dependencies`
        53cacf5 bump version to 3.4
        006e7ce rectify interactive parameter of rustic-cargo-check
        5a42347 Add documentation
        7206be4 Add rustic-cargo-update
        84ec9b2 allow config rustic-cargo-check-arguments on C-u
        6a99822 babel: update rustic-babel-default-toolchain as string type
        d71fbf5 babel: toolchain allows specify version string, close #439
        c5564b8 also allow parsing flycheck buffers to add missing dependencies
        db78dbf change cargo install arguments default
        92c2dde add workaround for rustic-format-file hang on windows
        760d48f make the prefix argument optional
        [...]
    ✓ (303/433) web-mode: 7b5459f -> 4b8a695 [1251 commit(s)]
        4b8a695 typescript indent fix
        a7f75a8 new color web-mode-interpolate-color4-face
        8c0baa2 better html interpolation
        de9dfa3 attr issue
        38ed4c5 perl template compatibility
        7ae48de Add completion for element tags
        c2f6ce3 Add completion and optional arguments to web-mode-attribute-insert
        0fbf102 Fix ‘{{~’ completion for Handlebars
        b060670 fixed: support multi line comment
        edf4237 fixed: web-mode-comment-indent-new-line
        cdbd74b fix css fontifying issue
        bbc34fe eex
        4f728fe add css colors' keywords
        8edf904 handle named colors in css
        036da13 add crystal engine
        1896ca2 web-mode.el: allow [.@?] prefixes for attributes in literal strings
        902b085 Added form_with for Ruby on Rails erb.html file
        f702777 some changes from Stephan Monnier
        4e3a7eb A typo in `:value-type`
        7ad06ca fix indent with else
        [...]
    ✓ (307/433) yaml-mode: 535273d -> 3fcb36d [10 commit(s)]
        a00de52 Add remaining highlighting tests
        9c26d32 Use separate font-lock test function
        45b232d Correct docstring
        fbf8a95 Make code less imperative
        ab69598 more fix
        85f19ca Fix by review
        ebeb27c Add unit test and github actions configuration
        211db42 Simplify regular expression
        e859daf fix: #96 highlight error with inline comments
        2f913f0 Fix byte-compile warnings
    ✓ (308/433) org-msg: 60e22e4 -> e017432 [1 commit(s)]
        e017432 Check if org-msg-options is already in mail body to avoid nesting
    ✓ (314/433) org-gcal.el: 229463a -> 40291be [1 commit(s)]
        6b06ffc Issue 202: Replace switch-to-buffer with set-buffer
    ✓ (315/433) emacs_chrome: 65a8e43 -> 3ce09c6 [1 commit(s)]
        341e0f2 Protect message from log data, especially when it may contain %. elements
    ✓ (317/433) alert: fb92919 -> 2c11cf9 [2 commit(s)]
        4512320 Add Termux support
        c39ce68 Remove executable bit from alert.el
    ✓ (318/433) telega.el: 11c0c78 -> 10bca59 [30 commit(s)]
        10bca59 [enh] Support for additional arguments to docker
        a02b9a7 etc/Dockerfile: update TDLib
        bb10ae6 Version -> 0.8.75
        e8bb33f telega-server: Mark heart on fire as emoji
        659f296 Bind <tab>/<backtab> in the `telega-msg-button-map'
        33a1188 Added :planet: emoji into etc/emojis.alist
        dbae662 Automatically view ignored message if all messages are read
        8071a84 Use --rm flag for docker
        108ed35 [enh] For telega-auto-translate-mode
        864ed69 Regard string values for `telega-use-docker'
        ba15890 New features, fixes and enhancements
        e94f6a1 Support wrap backwards from end of buffer
        e75bf96 [add] `is-bot' user temex
        c786170 Fix for the https://t.me/emacs_telega/36581
        4ac8c68 etc/Dockerfile update to TDLib 1.8.7
        70979c6 Back to melpa.org
        d88a481 Use MELPA mirror, since melpa.org is down
        549808d Support for TDLib 1.8.7
        37432b4 [add] Support for non-fe0f keycap sequence emojis
        1470d27 Various improvements and fixes
        [...]
    ✓ (319/433) emacs-everywhere: a1b16b5 -> b461c4b [4 commit(s)]
        b461c4b Update donation badge
        e1b7018 Try even harder to set the clipboard content
        c3d5d1a Fix calling of major mode function
        94e1069 Update maintainer email address
    ✓ (320/433) org-jira: 9362933 -> f6e9b90 [1 commit(s)]
        f6e9b90 Update TOC
    ✓ (323/433) pocket-reader.el: 88d1e60 -> eac22b2 [1 commit(s)]
        eac22b2 Docs: Remove image
    ✓ (326/433) elfeed-goodies: c9d9cd1 -> 544ef42 [4 commit(s)]
        3bd3ec2 Make face name consistent
        d0144d1 Faces are directly in elfeed-goodies group
        90b6951 Correctly define the faces
        fa0c6c6 Define faces for entry headers in show mode.
    ✓ (330/433) link-hint.el: 5461229 -> 1f9bb60 [1 commit(s)]
        1f9bb60 Added support for notmuch with w3m as renderer
    ✓ (331/433) bind-key was updated indirectly (with use-package)
    ✓ (333/433) dash.el: 0ac1ecf -> 3df46d7 [2 commit(s)]
        3df46d7 Give -concat alias a stable docstring
        e926385 Update GitHub CI workflow
    ✓ (334/433) s.el: 08661ef -> e957dcb [244 commit(s)]
        e957dcb Set a timeout on CI of 5 minutes.
        b4b8c03 1.13.1 add (s-unindent s &optional bol) (#155)
        2d2270b Delete ci-bugfix.yml
        abab87b Re-enable CI for 24.4&5 26.1,2&3
        04e864f Bugfix Github Workflow on 24.x/26.x (#160)
        ff1cc7d Run a CI workflow for bugfix/debugging  CI
        2d54cc7 Allow bug reports for 24.1-29.1
        d4fa4f6 Update BUG-REPORT.yml
        b528668 Update BUG-REPORT.yml
        fe44c1e Update BUG-REPORT.yml
        1b814c3 Update Bug Report
        9299e66 Align workflow name with dash.el
        be74a09 Disable CI for 24.4 & 24.5
        84941f2 Update readme-template.md
        06b4b0c Fix Bug Report YML string error.
        d283bae non-reproducible issue note to placeholder
        54f82f9 Update README copyright dates and maintainer note.
        27d41f7 Github actions replaces Travis badge.
        4839a3c Include Emacs 24.3..24.5 in CI tests.
        3c6b59d Set Emacs versions under test.
        [...]
    ✓ (335/433) f.el: d2019d4 -> d50dca4 [3 commit(s)]
        d50dca4 Fix package header and local variable format (#116)
        85c91f9 Update README
        9f7346b Silence Emacs 29 compiler warning (#115)
    ✓ (337/433) xref: feb30d2 -> cd3c12a [4 commit(s)]
    ✓ (339/433) emacsql was updated indirectly (with emacsql)
    ✓ (344/433) xml-rpc-el: b8c9c31 -> 85a9fc0 [8 commit(s)]
        b4409a0 Replace require of timezone with autoload
        97d609b Add .elpaignore for NonGNU ELPA
        f161262 Add NonGNU ELPA to installation instructions
        50d6a74 Fix link in NonGNU ELPA badge
        6d5892d Add file header to xml-rpc-test.el
        d3e467f Fix issues discovered by package-lint
        fc0c82e Bump version to 1.6.16
        aefa28c Fix byte-compiler warnings in Emacs 29
    ✓ (345/433) transient: 3b26742 -> ad953cc [16 commit(s)]
        ad953cc transient--insert-group: Add fallback for failed alignment calculation
        f98edf5 Backport commit db2ed9f333 from Emacs
        2143a95 Remove obsolete function aliases
        be4ffe8 manual: Fix mistake from previous commit
        277e5f2 transient-prepare-suffix{,es}: New functions
        e88f51d Quote more carefully while parsing
        afb7b25 make: Suppress warning about obsolete autoload package
        ea851f3 Turn suffix specifications into code instead of data
        0a3b22f transient--delay-post-command: Account for events returned as vector
        d93dfeb manual: Fix wrong reference
        097f5be manual: Fix typos
        555792f Fix setting level of anonymous infixes
        5b39231 transient--describe-function: Handle renamed help buffer better
        9d4fabc transient--describe-function: Handle renamed help buffer
        6b9c93a make: Print message for texi target
        8e5c384 manual: Drop an empty line
    ✓ (347/433) emacsql-sqlite was updated indirectly (with emacsql)
    ✓ (348/433) magit-section was updated indirectly (with magit)
    ✓ (351/433) pfuture: f9e67bd -> 19b53ae [2 commit(s)]
        19b53ae Fix eldoc warnings.
        61f66af Fix emacs native compilation warning
    ✓ (352/433) lv was updated indirectly (with hydra)
    ✓ (353/433) ht.el: c4c1be4 -> e83fdb8 [3 commit(s)]
        e83fdb8 Test ht-equal-p with more deeply nested ht
        ef768cc Make nested ht comparable
        cdc7666 Fix emacs native compilation warning
    ✓ (357/433) spinner: 34905ea -> 634529b [1 commit(s)]
        634529b Update spinner
    ✓ (358/433) svg-lib: 1e78346 -> da72b81 [1 commit(s)]
        da72b81 Update svg-lib
    ✓ (365/433) back-button: 98d9298 -> f8783c9 [2 commit(s)]
        0e79591 use cl-lib instead of cl
        d7b004a remove ucs-utils dependency
    ✓ (374/433) with-editor: cfcbc27 -> 4ca225b [4 commit(s)]
        4ca225b make: Suppress warning about obsolete autoload package
        1d5860c make: Print message for texi target
        14a958d manual: Regenerate texi
        3b8b2e0 manual: Use @insertcopying
    ✓ (375/433) git-gutter: 315e792 -> ec28e85 [3 commit(s)]
        c6547fe Ensure that global-linum-mode is bound when checking it
        cc2c145 tests(test.yml): Update Emacs 28.x to minor version 2
        9ff2f5c tests(test.yml): Add workflow_dispatch
    ✓ (379/433) expand-region.el: c5c4362 -> b70feaa [1 commit(s)]
        b70feaa Add autoload to contract-region
    ✓ (382/433) inheritenv: c2c879a -> 2102ed2 [1 commit(s)]
        2102ed2 Add Emacs 28.2 to CI, cut down size of matrix
    ✓ (383/433) emacs-language-id: 1d05bb7 -> 40ceb1f [3 commit(s)]
        40ceb1f Add HTML+EEX language-id (#23)
        f3dff98 add rescript-mode (#21)
        ba65c24 Recognize PHP in web-mode
    ✓ (386/433) popup-el: c65905a -> 5420f7f [6 commit(s)]
        5420f7f docs(README): use formal codeblock to hl code
        a9635a2 fix(popup.el): Use faster popup-replace-displayable implementation
        717c81e Make popup-replace-displayable much faster
        c303445 tests(test.yml): Update Emacs 28.x to minor version 2
        cc41181 Fix emacs native compilation warning
        34c2684 tests(test.yml): Add workflow_dispatch
    ✓ (387/433) string-inflection: fd7926a -> 50ad549 [3 commit(s)]
        a104cc1 Fix emacs native compilation warning
        1f91fa7 [Fix] Remove accidental copy/paste duplication
        0ccd59c [Feat] Add support for Elixir, which rarely uses UPPERCASE
    ✓ (393/433) lsp-docker: a0d7cbf -> 3ffd772 [1 commit(s)]
        3ffd772 Use a configurable docker command everywhere (#52)
    > In repository "closql", remote "origin" has URL
      "https://github.com/emacscollective/closql.git"
    but recipe specifies a URL of
      "https://github.com/magit/closql.git"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

      How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4)       Really delete remote "origin"? (y or n)     ✓ (400/433) closql: 87d2eda -> 820e951 [3 commit(s)]
        820e951 make: Suppress warning about obsolete autoload package
        463b0f4 closql-db: Value of process slot may no longer be a process
        46b3020 closql-where-class-in: Support vector or types as argument
    ✓ (401/433) ghub: 94f5aa2 -> 717f6b2 [6 commit(s)]
        717f6b2 make: Suppress warning about obsolete autoload package
        f07790b Use line-beginning-position instead of point-at-bol
        8d98f1e Silence deprecation warnings in backport
        4e5bb75 make: Print message for texi target
        41c5e50 manual: Regenerate texi
        0604dc5 manual: Use @insertcopying
    ✓ (402/433) treepy.el: 3ac940e -> de1a2dd [3 commit(s)]
        91829c8 Update library headers to follow conventions
        4f12d65 Enforce use of spaces for indentation
        f653124 Don't quote keys in cl-case
    ✓ (407/433) map: 9f46b9c -> 361f23d [1 commit(s)]
        361f23d Update map
    ✓ (408/433) multiple-cursors.el: 225fc0e -> 1e4842d [1 commit(s)]
        1e4842d Fix `mc/mark-all-in-region` leaving fake cursor.
    ✓ (411/433) package-lint: 70529b2 -> 4ea8318 [3 commit(s)]
        afa1cb5 Prefer pcase to cl-ecase (fixes #235)
        b04ea93 Regenerate stdlib-changes
        3dc5d14 Add Emacs 28.2
    ✓ (412/433) js2-mode: 841cfec -> a297ec2 [2 commit(s)]
        95fe268 Support top-level await
        7480c79 Recognize escaped $ inside template literal
    ✓ (416/433) php-runtime.el: 017e0e7 -> 36e6ae8 [3 commit(s)]
        36e6ae8 require cl-lib when compile-time
        71839d4 Remove dependency to f.el
        fbf0f4e Fix doc strings by checkdoc
    ✓ (420/433) rust-mode: 01ba441 -> b4537b6 [13 commit(s)]
        b96ea13 Fix internal link in README.md
        10be8b4 Use line-beginning-position instead of obsolete point-at-bol
        49087fd Skip test if Cargo isn’t installed.
        27e4d2b Avoid compilation warnings about potentially-undefined functions.
        c91d4dd rust-buffer-project: don't use rust-buffer-crate when file-remote-p
        49709dc Fulfil requirements of cargo locate-project --workspace
        faf6d98 Make compilation buffer workspace-aware
        d01b382 apply minor fixes
        da747ed more test fixing
        9d12986 fix quirks in rust-mode-tests.el
        6978752 fixes
        7bff488 bump version to 1.0.5
        56e5c3a Merge pull request #449 from rust-lang/remote-crate-path
    ✓ (422/433) request-deferred was updated indirectly (with emacs-request)
    ✓ (423/433) persist: 78c8d8f -> c108354 [1 commit(s)]
        c108354 Update persist
    ✓ (425/433) circe: 41cdc11 -> d0bd811 [1 commit(s)]
        d0bd811 Support strikethrough/monospace format codes
    ✓ (427/433) graphql.el: 5ca5f50 -> 4575642 [2 commit(s)]
        4575642 Mark copyright as now held by the FSF
        553850c Apply some cleanup patches from Stefan
    ✓ (432/433) popwin: 71a0ab2 -> 2165d34 [3 commit(s)]
        2165d34 tests(test.yml): Update Emacs 28.x to minor version 2
        16ae7c1 tests(test.yml): Add workflow_dispatch
        527216a tests(test.yml): Add workflow_dispatch
    ✓ Updated 180 package(s)
    > (Re)building packages...
      > Building use-package...
      > Building use-package > Building bind-key...
      > Building use-package...
      > Building straight...
      > Building all-the-icons...
      > Building helpful...
      > Building helpful > Building dash...
      > Building helpful > Building s...
      > Building helpful > Building f...
      > Building helpful...
      > Building projectile...
      > Building xref...
      > Building which-key...
      > Building shrface...
      > Building shrface > Building org...
      > Building shrface...
      > Building emacsql-mysql...
      > Building emacsql-mysql > Building emacsql...
      > Building emacsql-mysql...
      > Building copilot...
      > Building copilot > Building editorconfig...
      > Building copilot...
      > Building minibuffer-header...
      > Building mentor...
      > Building mentor > Building xml-rpc...
      > Building mentor > Building async...
      > Building mentor > Cloning url-scgi...
      > Building mentor > Building url-scgi...
      > Building mentor...
      > Building agraul-doom-themes...
      > Building devdocs...
      > Building clj-deps-new...
      > Building clj-deps-new > Building transient...
      > Building clj-deps-new > Building transient > Building compat...
      > Building clj-deps-new > Building transient...
      > Building clj-deps-new...
      > Building orca...
      > Building org-roam-ui...
      > Building org-roam-ui > Building org-roam...
      > Building org-roam-ui > Building org-roam > Building emacsql-sqlite...
      > Building org-roam-ui > Building org-roam > Building magit-section...
      > Building org-roam-ui > Building org-roam...
      > Building org-roam-ui...
      > Building treemacs...
      > Building treemacs > Building ace-window...
      > Building treemacs > Building ace-window > Building avy...
      > Building treemacs > Building ace-window...
      > Building treemacs > Building pfuture...
      > Building treemacs > Building hydra...
      > Building treemacs > Building hydra > Building lv...
      > Building treemacs > Building hydra...
      > Building treemacs > Building ht...
      > Building treemacs > Building posframe...
      > Building treemacs...
      > Building org-appear...
      > Building org-modern...
      > Building org-transclusion...
      > Building doct...
      > Building org-web-tools...
      > Building org-web-tools > Building request...
      > Building org-web-tools...
      > Building org-edit-indirect...
      > Building lsp-tailwindcss...
      > Building lsp-tailwindcss > Building lsp-mode...
      > Building lsp-tailwindcss > Building lsp-mode > Building spinner...
      > Building lsp-tailwindcss > Building lsp-mode > Building markdown-mode...
      > Building lsp-tailwindcss > Building lsp-mode...
      > Building lsp-tailwindcss...
      > Building corfu...
      > Building orderless...
      > Building kind-icon...
      > Building kind-icon > Building svg-lib...
      > Building kind-icon...
      > Building cape...
      > Building company...
      > Building vertico...
      > Building consult...
      > Building consult-dir...
      > Building consult-flycheck...
      > Building consult-flycheck > Building flycheck...
      > Building consult-flycheck...
      > Building embark...
      > Building embark-consult...
      > Building marginalia...
      > Building all-the-icons-completion...
      > Building vertico-posframe...
      > Building doom-themes...
      > Building back-button...
      > Building hl-todo...
      > Building doom-modeline...
      > Building evil-anzu...
      > Building evil-anzu > Building evil...
      > Building evil-anzu...
      > Building treemacs-evil...
      > Building treemacs-projectile...
      > Building treemacs-magit...
      > Building treemacs-magit > Building magit...
      > Building treemacs-magit > Building magit > Building git-commit...
      > Building treemacs-magit > Building magit > Building git-commit > Building with-editor...
      > Building treemacs-magit > Building magit > Building git-commit...
      > Building treemacs-magit > Building magit...
      > Building treemacs-magit...
      > Building treemacs-persp...
      > Building treemacs-persp > Building persp-mode...
      > Building treemacs-persp...
      > Building lsp-treemacs...
      > Building git-gutter...
      > Building evil-embrace...
      > Building evil-embrace > Building expand-region...
      > Building evil-embrace...
      > Building evil-nerd-commenter...
      > Building evil-collection...
      > Building yasnippet...
      > Building ts-fold...
      > Building format-all...
      > Building format-all > Building inheritenv...
      > Building format-all > Building language-id...
      > Building format-all...
      > Building auto-yasnippet...
      > Building doom-snippets...
      > Building ctrlf...
      > Building diredfl...
      > Building dirvish...
      > Building ibuffer-vc...
      > Building info-colors...
      > Building browse-at-remote...
      > Building git-timemachine...
      > Building git-modes...
      > Building eshell-syntax-highlighting...
      > Building vterm...
      > Building popup...
      > Building spell-fu...
      > Building citar...
      > Building citar > Building parsebib...
      > Building citar > Building citeproc...
      > Building citar > Building citeproc > Building string-inflection...
      > Building citar > Building citeproc...
      > Building citar...
      > Building citar-embark...
      > Building howdoyou...
      > Building realgud...
      > Building dap-mode...
      > Building dap-mode > Building lsp-docker...
      > Building dap-mode...
      > Building envrc...
      > Building docker...
      > Building dockerfile-mode...
      > Building quickrun...
      > Building lsp-ui...
      > Building consult-lsp...
      > Building forge...
      > Building forge > Building closql...
      > Building forge > Building ghub...
      > Building forge > Building ghub > Building treepy...
      > Building forge > Building ghub...
      > Building forge...
      > Building magit-todos...
      > Building makefile-executor...
      > Building pass...
      > Building pass > Building password-store...
      > Building pass...
      > Building pdf-tools...
      > Building kurecolor...
      > Building tree-sitter-langs...
      > Building evil-textobj-tree-sitter...
      > Building osx-trash...
      > Building paredit...
      > Building map...
      > Building clojure-mode...
      > Building clj-refactor...
      > Building clj-refactor > Building multiple-cursors...
      > Building clj-refactor > Building cider...
      > Building clj-refactor...
      > Building elisp-demos...
      > Building flycheck-package...
      > Building flycheck-package > Building package-lint...
      > Building flycheck-package...
      > Building buttercup...
      > Building js2-mode...
      > Building typescript-mode...
      > Building lua-mode...
      > Building grip-mode...
      > Building nix-mode...
      > Building nix-update...
      > Building org-contrib...
      > Building orgit...
      > Building orgit-forge...
      > Building org-download...
      > Building gnuplot...
      > Building alert...
      > Building org-tree-slide...
      > Building org-re-reveal...
      > Building revealjs...
      > Building ob-restclient...
      > Building ob-restclient > Building restclient...
      > Building ob-restclient...
      > Building php-runtime...
      > Building php-mode...
      > Building phpactor...
      > Building lsp-pyright...
      > Building anaconda-mode...
      > Building python-pytest...
      > Building pyimport...
      > Building restclient-jq...
      > Building rustic...
      > Building rustic > Building rust-mode...
      > Building rustic...
      > Building web-mode...
      > Building yaml-mode...
      > Building org-msg...
      > Building org-gcal...
      > Building org-gcal > Building request-deferred...
      > Building org-gcal > Building persist...
      > Building org-gcal...
      > Building edit-server...
      > Building circe...
      > Building telega...
      > Building emacs-everywhere...
      > Building org-jira...
      > Building graphql...
      > Building pocket-reader...
      > Building elfeed-goodies...
      > Building elfeed-goodies > Building popwin...
      > Building elfeed-goodies > Building link-hint...
      > Building elfeed-goodies...
      ✓ Rebuilt 187 package(s)
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    > Purging ELPA packages...
      ✓ Deleted archives
      ✓ Deleted gpg
    > Purging straight repositories...
      ✓ Purged repos/diff-hl
      ✓ Purged repos/emacs-spell-fu
      ✓ Purged repos/gh-notify
      ✓ Purged repos/github-explorer
      ✓ Purged repos/github-search
      ✓ Purged repos/github-stars.el
      ✓ Purged repos/lsp-bridge
      ✓ Purged repos/mastodon
    > Regrafting 415 repos...
      ✓ Finished regrafting. Size before: 0.0KB and after: 0.0KB (0.0KB)
    > Purging old native bytecode...
      - Deleting "28.1-32bb1b2d"
      ✓ Purged 1 directory(ies)
  > (Re)building profile in /Users/nopan/.config/emacs/.local/etc/...
    > Deleting old init files...
    > Generating 4 init files...
    > Byte-compiling ~/.config/emacs/.local/etc/@init.28.el...
    ✓ Built init.28.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
✓ Finished in 18m 12s
** <2022-11-04 Fri 03:18>
> Tangling your literate config...
  ✓ Done tangling 42 file(s)!
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    ✓ melpa updated (e3da6cf -> 1b2c64c)
      - $ cd /Users/nopan/.config/emacs/.local/straight/repos/melpa/
        $ git config --get remote.origin.url

        https://github.com/melpa/melpa.git

        [Return code: 0]

        $ cd /Users/nopan/.config/emacs/.local/straight/repos/melpa/
        $ git fetch origin

        From https://github.com/melpa/melpa
           e3da6cf0..1b2c64ce  master     -> origin/master
    ✓ nongnu-elpa updated (b1d7b18 -> 057dc59)
      - $ cd /Users/nopan/.config/emacs/.local/straight/repos/nongnu-elpa/
        $ git config --get remote.origin.url

        https://git.savannah.gnu.org/git/emacs/nongnu.git

        [Return code: 0]

        $ cd /Users/nopan/.config/emacs/.local/straight/repos/nongnu-elpa/
        $ git fetch origin

        From https://git.savannah.gnu.org/git/emacs/nongnu
           b1d7b18..057dc59  main       -> origin/main
    ✓ gnu-elpa-mirror updated (a4f8d64 -> 97a6cf7)
      - $ cd /Users/nopan/.config/emacs/.local/straight/repos/gnu-elpa-mirror/
        $ git config --get remote.origin.url

        https://github.com/emacs-straight/gnu-elpa-mirror.git

        [Return code: 0]

        $ cd /Users/nopan/.config/emacs/.local/straight/repos/gnu-elpa-mirror/
        $ git fetch origin

        From https://github.com/emacs-straight/gnu-elpa-mirror
           a4f8d64..97a6cf7  master     -> origin/master
    ✓ emacsmirror-mirror updated (be9d095 -> 66865c4)
      - $ cd /Users/nopan/.config/emacs/.local/straight/repos/emacsmirror-mirror/
        $ git config --get remote.origin.url

        https://github.com/emacs-straight/emacsmirror-mirror.git

        [Return code: 0]

        $ cd /Users/nopan/.config/emacs/.local/straight/repos/emacsmirror-mirror/
        $ git fetch origin

        From https://github.com/emacs-straight/emacsmirror-mirror
           be9d095..66865c4  master     -> origin/master
  > Updating packages (this may take a while)...
    > In repository "emacsql", remote "origin" has URL
      "https://github.com/skeeto/emacsql.git"
    but recipe specifies a URL of
      "https://github.com/magit/emacsql.git"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

    ✓ (54/433) lsp-tailwindcss: c0ca58d -> 6e5addf [1 commit(s)]
        6e5addf feat: bump server version to 0.9.1 (#48)
    ✓ (55/433) corfu: 03688d6 -> 17f3c28 [1 commit(s)]
        17f3c28 Update corfu
    ✓ (81/433) doom-modeline: b66d5e5 -> 87b9289 [4 commit(s)]
        87b9289 Eliminate compilation warnings.
        3005b87 Improve faces of modals segments.
        5d9c20a [Feature] Different color indicators for various modal modes.
        729c9a8 Add option to make segments visible in inactive windows (#588)
    ✓ (99/433) evil: 26168f1 -> f921816 [2 commit(s)]
        f921816 Add evil-keep-lines and evil-flush-lines
        e0e68d0 Flush and keep for evil-ex-global performance
    ✓ (139/433) magit: 87e68e0 -> 2a5815f [4 commit(s)]
        2a5815fe git-commit-font-lock-keywords-1: Use more restrictive keyword regexp
        a3d3758b magit-file-rename: Fix initial-input for destination
        1f74e797 magit-rebase-interactive-1: Cosmetics
        2653432b git-rebase: Support update-ref action
    ✓ (150/433) emacs-libvterm: 19c84e9 -> 5de2684 [1 commit(s)]
        5de2684 Change a binding for S-prior back to scroll-down-command
    ✓ (182/433) lsp-mode: dfda673 -> 54cdc61 [6 commit(s)]
        54cdc61 fix: support volar 1.0 (#3787)
        0fb8fe3 add references capability (#3798)
        145ca1e add .gradle to `lsp-file-watch-ignored-directories` (#3797)
        8091f5d Update docs
        06bd589 Fix lsp-clients.json as well.
        b8d9b0a Do not use 'nil for the nix nil server id (#3795)
    ✓ (184/433) consult-lsp: 58b5414 -> f6fff70 [1 commit(s)]
        f6fff70 fix(file-symbols): use symbol in lsp-get
    ✓ (185/433) magit was updated indirectly (with magit)
    > In repository "makefile-executor.el", remote "origin" has URL
      "https://github.com/thiderman/makefile-executor.el.git"
    but recipe specifies a URL of
      "https://github.com/Olivia5k/makefile-executor.el.git"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

    > In repository "macrostep", remote "origin" has URL
      "https://github.com/joddie/macrostep.git"
    but recipe specifies a URL of
      "https://github.com/emacsorphanage/macrostep.git"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

      How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4)       Really delete remote "origin"? (y or n)     ✓ (215/433) macrostep: 424e373 -> 75ecd04 [10 commit(s)]
        75ecd04 Require ert and cl-lib unconditionally
        22c10f9 Delete bundled cl-lib.el and ert.el
        b430ea8 Add .elpaignore
        1596a7c Checkdoc fixes
        400c483 Add LICENSE
        4c3c260 Update library headers
        049282b Shorten first lines of two docstrings
        290e412 Remove stray declare form
        2d0091b Avoid positional arguments to define-minor-mode
        abed4cb Continue to extend macrostep-expansion-highlight-face to window edge
    ✓ (276/433) php-mode: c3c442a -> f5c4016 [13 commit(s)]
        f5c4016 Update AUTHORS
        9603a4f Revert string-trim-right
        08ef915 Revert "Use compat-string-trim-* functions for compatibility"
        cf10f7c Use compat-string-trim-* functions for compatibility
        f35bf9a Add php-mode-version-id and make obsolete php-mode-version-number
        7853345 Update CHANGELOG
        258d6c5 Add Psalm template annotations to php-phpdoc-type-tags
        0bbdc46 Add "type" to php-phpdoc-type-tags as "phpstan-type"
        44601ab Add "phan" to type tag vendor prefix
        08776c1 Changed variable name to php-phpdoc-type-names to avoid confusion
        fe8ab09 Add key-of and value-of type (#716)
        3321d49 Add @param-out keyword in php-phpdoc-type-tags (#715)
        235c9a0 Add @phpstan-self-out and @phpstan-this-out keywords (#714)
    ✓ (282/433) emacs-async: ffde304 -> 10cedd8 [1 commit(s)]
        91bd569 dired-async: Explicitly tag dired-async processes
    ✓ (318/433) telega.el: 10bca59 -> 31a695a [1 commit(s)]
        31a695a Correct a trivial event message misspelling (#382)
    > In repository "mastodon.el", remote "origin" has URL
      "https://github.com/jdenen/mastodon.el.git"
    but recipe specifies a URL of
      "https://codeberg.org/martianh/mastodon.el.git"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

      How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4)       Really delete remote "origin"? (y or n)     > In repository "mastodon.el", HEAD on "master" is behind default branch "main"

         1) Abort
         2) Checkout "main"
         3) Magit log "master..main" and open recursive edit

      How to proceed? (1, 2, 3)     ✓ (322/433) mastodon.el: ef10fe5 -> 2d25c15 [917 commit(s)]
        50bd192 Revert "FIX getting of 'parent-toot properties in mastodon-toot--reply"
        7b5b03b get instance from account/url, so it works for ppl on own instance
        0b7c807 t = yes, :json-false = no, in instance description display
        e07ccef FIX fetching parent toot in --reply, for notifs
        f324c1c woodpecker 27 not 27.1
        57bc256 Revert "mandate 27.1 for woodpecker (debian stable)"
        220a883 mandate 27.1 for woodpecker (debian stable)
        7dc15fc separate pipline names + only CI on main/develop
        56d305e separate pipline names + only CI on main/develop
        7a4e4e0 add emacs 27 to woodpecker
        604fe15 add emacs 27 to woodpecker
        c0a267f add emacs 27 to woodpecker
        56b820e check version in woodpecker
        cf02b35 autoload profile-account-settings in mastodon.el
        6b88c28 handle empty relationships vector in make-buffer-for
        0798cf6 handle empty relationships vector in make-buffer-for
        020c8ef FIX getting of 'parent-toot properties in mastodon-toot--reply
        c917a2d FIX getting of 'parent-toot properties in mastodon-toot--reply
        e8432a9 FIX getting of 'parent-toot properties in mastodon-toot--reply
        9420b5e FIX getting of 'parent-toot properties in mastodon-toot--reply
        [...]
    ✓ (349/433) magit-section was updated indirectly (with magit)
    ✓ Updated 15 package(s)
    > (Re)building packages...
      > Building async...
      > Building magit-section...
      > Building lsp-tailwindcss...
      > Building lsp-tailwindcss > Building lsp-mode...
      > Building lsp-tailwindcss...
      > Building corfu...
      > Building doom-modeline...
      > Building evil...
      > Building magit...
      > Building magit > Building git-commit...
      > Building magit...
      > Building vterm...
      > Building consult-lsp...
      > Building macrostep...
      > Building php-mode...
      > Building telega...
      > Building mastodon...
      ✓ Rebuilt 15 package(s)
  > Purging orphaned packages (for the emperor)...
    > Purging straight builds...
      ✓ Purged build/ucs-utils
    - No ELPA packages to purge
    > Purging straight repositories...
      ✓ Purged repos/spell-fu
      ✓ Purged repos/ucs-utils
    > Regrafting 414 repos...
      ✓ Finished regrafting. Size before: 0.0KB and after: 0.0KB (0.0KB)
    > Purging old native bytecode...
      - Deleting "28.2-48ec18bb"
      ✓ Purged 1 directory(ies)
  > (Re)building profile in /Users/nopan/.config/emacs/.local/etc/@/...
    > Deleting old init files...
    > Generating 4 init files...
    > Byte-compiling ~/.config/emacs/.local/etc/@init.28.el...
    ✓ Built init.28.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
✓ Finished in 17m 28s
