#+TITLE:   packages
#+DATE:    Oct 6, 2021
#+SINCE:   v3.0.0-alpha
#+STARTUP: inlineimages nofold

* Packages inbox
#+begin_src emacs-lisp :tangle yes
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

(unpin! t)            ; unpin packages
;; Extend shr/eww with org features and analysis capability
(package! shrface)
#+end_src

* System administration
#+begin_src emacs-lisp :tangle yes
;;
;;; Tools

(package! dtache
  ;; Run shell cmds in sessions that are isolated from Emacs
  :recipe (:host gitlab :repo "niklaseklund/dtache"))
(unless IS-MAC
 (package! keychain-environment))
(package! trashed)
#+end_src

* Personalization
#+begin_src emacs-lisp :tangle yes
;;
;;; UI
#+end_src

** Themes
#+begin_src emacs-lisp :tangle no
;;; Themes
(package! alabaster
  :recipe (:host github :repo "wandersoncferreira/alabaster-theme"))
(package! quartz :recipe (:host github :repo "fm0xb/quartz-theme.el"))
(package! moe-theme)
(package! gotham-theme)
(package! vs-dark-theme)
#+end_src

*** in use :enabledThemes:
#+begin_src emacs-lisp :tangle yes
;;; Themes
(package! autothemer)
(package! catppuccin
  :recipe (:host github :repo "konrad1977/emacs" :files ("themes/cat*")))
(package! kanagawa
  :recipe (:host github :repo "konrad1977/emacs" :files ("themes/kana*")))
#+end_src

** Miscellaneous
#+begin_src emacs-lisp :tangle yes
;;; Miscellaneous
#+end_src


* Modules
Private or extra to the Doom modules
#+begin_src emacs-lisp :tangle yes
;;
;;; Modules
#+end_src

** App
*** Jira :jira:org:bug:tracker:
#+begin_src emacs-lisp :tangle modules/app/jira/packages.el :mkdirp yes
;; -*- no-byte-compile: t; -*-
;;; app/jira/packages.el

(package! org-jira)
#+end_src

*** Reddit :reddit:browse:news:
#+begin_src emacs-lisp :tangle modules/app/reddit/packages.el
;; -*- no-byte-compile: t; -*-
;;; app/reddit/packages.el

(package! md4rd)
#+end_src

*** Slack :tools:
#+begin_src emacs-lisp :tangle modules/app/slack/packages.el :mkdirp yes
;; -*- no-byte-compile: t; -*-
;;; app/slack/packages.el

(package! slack)
#+end_src

** Completion
*** Company
#+begin_src emacs-lisp :tangle yes
;;; :completion company +tabnine
(when (featurep! :completion company +tabnine)
  (package! company-tabnine
    :recipe (:host github :repo "tommyX12/company-tabnine")))
#+end_src
*** Vertico
#+begin_src emacs-lisp :tangle yes
;;; :completion vertico +childframe
(when (featurep! :completion vertico +childframe)
  (package! vertico-posframe))
#+end_src

** Editor
*** evil
#+begin_src emacs-lisp :tangle yes
;;; :editor evil +tree-sitter
(when (and (featurep! :editor evil +tree-sitter)
           (featurep! :tools tree-sitter))
  (package! evil-textobj-tree-sitter
    :recipe (:host github
             :repo "meain/evil-textobj-tree-sitter"
             :files (:defaults "queries"))))
#+end_src

** Emacs

*** ctrlf :extension:
#+begin_src emacs-lisp :tangle modules/emacs/ctrlf/packages.el :mkdirp yes
;; -*- no-byte-compile: t; -*-
;;; emacs/ctrlf/packages.el

(package! ctrlf)
#+end_src

*** dired :files:convenience:
#+begin_src emacs-lisp :tangle yes
;;; :emacs dired +dirvish
(when (featurep! :emacs dired +dirvish)
  (package! dirvish))
#+end_src

*** info
#+begin_src emacs-lisp :tangle modules/emacs/info/packages.el  :mkdirp yes
;; -*- no-byte-compile: t; -*-
;;; emacs/info/packages.el

(package! info-colors)
#+end_src

** OS :os:
*** Windows Subsystem Linux :wsl:
#+begin_src emacs-lisp :tangle modules/os/wsl/packages.el
;; -*- no-byte-compile: t; -*-
;;; os/wsl/packages.el -*- lexical-binding: t; -*-

(let ((distro (doom-system-distro)))
  (when (or (eq 'ubuntu distro) (eq 'debian distro)) (package! debian-el)))
#+end_src
** Tools
*** Brief
#+begin_src emacs-lisp :tangle modules/tools/brief/packages.el
;; -*- no-byte-compile: t; -*-
;;; tools/brief/packages.el

(package! cheat-sh) ; tldr but more detail, weaker syntax highlight
(package! howdoyou
  :recipe (:host github :repo "thanhvg/emacs-howdoyou"))
(package! tldr)
#+end_src
*** kubernetes
#+begin_src emacs-lisp :tangle modules/tools/kubernetes/packages.el :mkdirp yes
;; -*- no-byte-compile: t; -*-
;;; tools/kubernetes/packages.el

(package! kubernetes)
(package! kubedoc)
#+end_src
*** Leetcode :extension:tools:
#+begin_src emacs-lisp :tangle modules/tools/leetcode/packages.el :mkdirp yes
;; -*- no-byte-compile: t; -*-
;;; tools/leetcode/packages.el

(package! leetcode)
#+end_src
*** Lookup
#+begin_src emacs-lisp :tangle yes
;;; :tools lookup +devdocs 
(when (featurep! :tools lookup +devdocs) (package! devdocs))
#+end_src

*** Magit
#+begin_src emacs-lisp :tangle yes
;;; :tools magit +forge
(when (and EMACS29+ (featurep! :tools magit +forge))
 (package! emacsql-sqlite-builtin
  :recipe (:host github :repo "tarsiiformes/emacsql"
           :branch "sqlite-backends")))
#+end_src
** Lang
*** Clojure
#+begin_src emacs-lisp :tangle yes
;;; :lang clojure
(when (featurep! :lang clojure) (package! clj-deps-new))
#+end_src
*** Org
#+begin_src emacs-lisp :tangle yes
;;; :lang org
(package! orca)       ; Org Capture
(package! org-roam-ui)
(when (featurep! :lang org +web) (package! org-web-tools))
#+end_src
*** Web
#+begin_src emacs-lisp :tangle yes
;;; :lang web +tailwind
(when (and (featurep! :tools lsp) (featurep! :lang web +tailwind))
  (package! lsp-tailwindcss
    :recipe (:host github :repo "merrickluo/lsp-tailwindcss")))
#+end_src

** UI
*** Fixmee :navigation:convenience:
#+begin_src emacs-lisp :tangle modules/ui/fixmee/packages.el
;; -*- no-byte-compile: t; -*-
;;; ui/fixmee/packages.el

(package! fixmee)
#+end_src
*** Discover
#+begin_src emacs-lisp :tangle modules/ui/discover/packages.el :mkdirp yes
;; -*- no-byte-compile: t; -*-
;;; ui/discover/packages.el

(package! discover)
#+end_src

* Doom packages.el's Documentation
To install a package with Doom you must declare them here and run 'doom sync'
on the command line, then restart Emacs for the changes to take effect -- or
use 'M-x doom/reload'.


To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
#+begin_src emacs-lisp :tangle no
(package! some-package)
#+end_src

To install a package directly from a remote git repo, you must specify a
`:recipe'. You'll find documentation on what `:recipe' accepts here:
https://github.com/raxod502/straight.el#the-recipe-format
#+begin_src emacs-lisp :tangle no
(package! another-package
 :recipe (:host github :repo "username/repo"))
#+end_src

If the package you are trying to install does not contain a PACKAGENAME.el
file, or is located in a subdirectory of the repo, you'll need to specify
`:files' in the `:recipe':
#+begin_src emacs-lisp :tangle no
(package! this-package
 :recipe (:host github :repo "username/repo"
          :files ("some-file.el" "src/lisp/*.el")))
#+end_src

If you'd like to disable a package included with Doom, you can do so here
with the `:disable' property:
#+begin_src emacs-lisp :tangle no
(package! builtin-package :disable t)
#+end_src

You can override the recipe of a built in package without having to specify
all the properties for `:recipe'. These will inherit the rest of its recipe
from Doom or MELPA/ELPA/Emacsmirror:
#+begin_src emacs-lisp :tangle no
(package! builtin-package :recipe (:nonrecursive t))
(package! builtin-package-2 :recipe (:repo "myfork/package"))
#+end_src

Specify a `:branch' to install a package from a particular branch or tag.
This is required for some packages whose default branch isn't 'master' (which)
our package manager can't deal with; see raxod502/straight.el#279)
(package! builtin-package :recipe (:branch "develop"))

Use `:pin' to specify a particular commit to install.
#+begin_src emacs-lisp :tangle no
(package! builtin-package :pin "1a2b3c4d5e")
#+end_src


Doom's packages are pinned to a specific commit and updated from release to
release. The `unpin!' macro allows you to unpin single packages...
#+begin_src emacs-lisp :tangle no
(unpin! pinned-package)
#+end_src
...or multiple packages
#+begin_src emacs-lisp :tangle no
(unpin! pinned-package another-pinned-package)
#+end_src
...Or *all* packages (NOT RECOMMENDED); will likely break things)
#+begin_src emacs-lisp :tangle no
(unpin! t)
#+end_src
